lib/run_loop/core.rb, lib/run_loop/version.rb, run_loop.gemspec, scripts/calabash_script_uia.js, scripts/run_loop_host.js, scripts/timeout3
This pull request ensures that we can't get a hanging read-cmd.sh process on the host
=> Set timeout on max duration of reading from fifo in :host

.irbrc, run_loop.gemspec, spec/spec_helper.rb
Awesome print has fixed the '==' bug so we can remove the monkey patches.
**Should make "==" usage safer** [#154](https://github.com/michaeldv/awesome_print/issues/154)
=> Feature/update awesome print to 1.6

run_loop.gemspec
Test cloud gem is ready to update.
ATTN: @skovsboll
=> Relax retriable to < 2.0, >= 1.3.3.1

lib/run_loop/core.rb, lib/run_loop/xctools.rb, spec/lib/core_spec.rb, spec/lib/xctools_spec.rb, spec/resources.rb
=> Adds Xcode 6.3 beta support

lib/run_loop.rb, lib/run_loop/process_terminator.rb, spec/integration/process_terminator_spec.rb, spec/lib/process_terminator_spec.rb
We will need to terminate lldb processes as well as instruments processes.
=> Migrate process kill+wait out of instruments

.travis.yml
=> Turn off travis slack notifications

lib/run_loop/core.rb, lib/run_loop/xctools.rb, spec/lib/core_spec.rb, spec/lib/xctools_spec.rb
Xcode 6.4 beta has been released.
=> Xcode 6.4b support

lib/run_loop/environment.rb, lib/run_loop/host_cache.rb, spec/lib/environment_spec.rb, spec/lib/host_cache_spec.rb
@kasperlanger convinced me that caching to /tmp/ was not advisable.
=> Move host cache from /tmp to ~/.run-loop

lib/run_loop/cli/simctl.rb, lib/run_loop/simctl/bridge.rb
Xcode 7 simulators are prone to crashing.  I have determined that killing the CoreSimulator daemon can help.
```
$ be run-loop simctl refresh
$ be run-loop simctl refresh --debug
$ be run-loop simctl help refresh
Usage:
run-loop refresh
Options:
-v, [--debug], [--no-debug]  # Enable debug logging.
EXPERIMENTAL: Terminate CoreSimulatorService daemons
```
Note:  the 'Usage:' for subcommands is incorrect - this is a known bug in thor.
=> Managing the CoreSimulator daemon

lib/run_loop/xcode.rb, spec/lib/xcode_spec.rb
Sometimes you just have to know.
=> Implement Xcode#beta? 

lib/run_loop/core.rb, spec/lib/core_spec.rb
=> Default sim for Xcode 7 is 'iPhone 5s (9.0)'

lib/run_loop/instruments.rb, spec/lib/instruments_spec.rb
Fixup how we filter the host machine from instruments output.
=> Stabilize instruments examples on travis

lib/run_loop.rb, lib/run_loop/device.rb, lib/run_loop/instruments.rb, lib/run_loop/regex.rb, lib/run_loop/sim_control.rb, lib/run_loop/xcode.rb, spec/resources.rb
I got tired of chasing common regex expressions around the sources.
=> Regex module

lib/run_loop/app.rb, lib/run_loop/device.rb, lib/run_loop/host_cache.rb, lib/run_loop/instruments.rb, lib/run_loop/ipa.rb, lib/run_loop/l10n.rb, lib/run_loop/lipo.rb, lib/run_loop/version.rb, lib/run_loop/xcode.rb
Clean up irb and pry console output.
=> #to_s and #inspec methods for gem classes

scripts/run_loop_fast_uia.js, scripts/run_loop_host.js, scripts/run_loop_shared_element.js
iOS 9 has different text for Apple Push Notifications privacy alerts.
=> JS: can dismiss iOS 9 APNS privacy alerts

lib/run_loop/device.rb, spec/lib/device_spec.rb
Need a faster way to update the simulator states.
=> Simulator devices can update their state

lib/run_loop/core.rb, lib/run_loop/xcode.rb, lib/run_loop/xctools.rb, spec/lib/core_spec.rb, spec/lib/xcode_spec.rb, spec/lib/xctools_spec.rb
* Xcode
* Core.default_simulator
* XCTools (deprecated)
=> Xcode 7.1 beta support

lib/run_loop/core.rb, spec/lib/core_spec.rb
**deprecate or fix Core.simulator_target?** #218
Fixing was easier, but I think it should be deprecated.
=> Fixup Core#simulator_target?

lib/run_loop/core.rb
It was hard to see the forest through the trees.
I was working on **Catch iOS Simulator errors when launching with instruments and retry** #242 and realized I could not make easy sense of the existing code.
=> Whitespace and formatting for run with options

lib/run_loop/dot_dir.rb, spec/lib/dot_dir_spec.rb
@olefriis pointed out that I could do a better job generating timestamped directories.
=> DotDir does a better job of creating unique, time stamped directories

.travis.yml, README.md, lib/run_loop.rb, lib/run_loop/xcrun.rb, run_loop.gemspec, spec/lib/xcrun_spec.rb, spec/spec_helper.rb
Gems that we depend on are dropping ruby 1.9 support and it is has become a burden to maintain.
=> Set minimum ruby version to 2.0

.rspec, Rakefile, run_loop.gemspec, scripts/ci/jenkins/rspec-unit.sh, spec/integration/launch_sim_with_udid_spec.rb, spec/integration/run_sim_spec.rb, spec/integration/simulator_compatibility_spec.rb, spec/lib/instruments_spec.rb, spec/resources.rb
The ultimate goal is run-loop against supported Xcode versions on the Calabash CI Jenkins machine.
At the moment we only run the rspec _unit_ tests on Travis because the integration tests are too flakey for virtual machines.
The hope is that we can run the _integration_ tests on Jenkins. We'll start by running just the rspec unit tests.
Progress on the epic **Integration examples need attention** #243
=> Standup Jenkins jobs

.travis.yml, CHANGELOG.md, lib/run_loop/environment.rb, lib/run_loop/sim_control.rb, spec/lib/environment_spec.rb
Completes:
* deprecate CAL_SIM_POST_LAUNCH_WAIT env variable #298
Progress on:
* Integration examples need attention #243
* Deprecate SimControl #320
=> Remove  CAL_SIM_POST_LAUNCH_WAIT env var

scripts/run_loop_fast_uia.js, scripts/run_loop_host.js, scripts/run_loop_shared_element.js
We haven't been able to reliably generate this kind of alert.
Partial fix for:
**Unable to touch buttons on OS level permission alerts** #324
=> Auto dismiss "nearby bluetooth devices" alert

scripts/calabash_script_uia.js
Ensure that we always deliver a main window with a hitpoint. Fixes edge case for apps where main window is not on screen. Corresponds to build of commit:
https://github.com/krukow/calabash-script/commit/7e54beab5aa83087c7b52a55eca3d1828d2d0f36
=> Find window with hitpoint

scripts/run_loop_fast_uia.js, scripts/run_loop_host.js, scripts/run_loop_shared_element.js
Resolves **Add Danish missing localization for Location alert** #346
=> Privacy: dismiss Danish Location alert

CHANGELOG.md
=> Corrected name in CHANGELOG.md

lib/run_loop/core.rb, lib/run_loop/xcode.rb, spec/lib/core_spec.rb, spec/lib/xcode_spec.rb
Resolves **No default simulator for Xcode 7.2** #352
=> Xcode 7.2 support

lib/run_loop.rb, spec/integration/run_loop_spec.rb, spec/lib/run_loop_spec.rb
* Resolves **Unable to find file: run_loop_fast_uia.js** #361
* Replaces **Hotfix/2.0.3** #363
=> Fix cannot find run loop script bug

.irbrc, lib/run_loop.rb, lib/run_loop/environment.rb, lib/run_loop/http/error.rb, lib/run_loop/http/request.rb, lib/run_loop/http/retriable_client.rb, lib/run_loop/http/server.rb, lib/run_loop/xcuitest.rb, run_loop.gemspec, spec/lib/environment_spec.rb, spec/lib/http/request_spec.rb, spec/lib/http/retriable_client_spec.rb, spec/lib/http/server_spec.rb, spec/lib/xcuitest_spec.rb
We are experimenting with replacing UIAutomation with a XCUITest driver.
```
$ be irb
> xcuitest.launch_calabus_driver
> xcuitest.launch_app
```
This is a WIP that should be merged.
=> Support for launching the Calabus Driver and apps via the bus driver

.irbrc, lib/run_loop/xcuitest.rb, spec/lib/xcuitest_spec.rb
This PR makes run-loop compatible with the CBXDriver changes: **Project structure and style ** [#24](https://github.com/calabash/calabash-xcuitest-server/pull/24)
ATTN @sapieneptus
=> Respond to CBXDriver project changes

lib/run_loop/app.rb, spec/lib/app_spec.rb
Progress on **0.18.1 Cannot automatically detect .app** [#1008](https://github.com/calabash/calabash-ios/issues/1008)
Some .app bundles in DerivedData do _not_ contain an executable file.
=> App: valid apps have an executable file (CFBundleExecutable)

.irbrc, lib/run_loop/environment.rb, lib/run_loop/http/retriable_client.rb, lib/run_loop/xcuitest.rb, spec/integration/xcuitest_spec.rb, spec/lib/environment_spec.rb, spec/lib/xcuitest_spec.rb, spec/resources.rb
```
device = Resources.shared.default_simulator
bundle_identifier = "com.apple.Preferences"
xcuitest = RunLoop::XCUITest.new(bundle_identifier, device)
xcuitest.launch
```
=> Interface for launching CBX-Runner

.irbrc, lib/run_loop.rb, lib/run_loop/core.rb, lib/run_loop/http/retriable_client.rb, lib/run_loop/xcuitest.rb, spec/lib/xcuitest_spec.rb
We want an interface to the CBX-Runner.
This is a first pass at an API for launching and sending commands.
There are a number of issues that need to be resolved on the server before this interface can be completed.
=> Experimental interface for launching CBX-Runner and sending commands

lib/run_loop/dot_dir.rb, spec/lib/dot_dir_spec.rb
This will make debugging issues involving run_loop.out easier.
=> DotDir: symlink to current result

lib/run_loop/core_simulator.rb, spec/lib/core_simulator_spec.rb
On Jenkins, we are seeing flickering tests because simctl fails to launch the app.
We are investigating two possible problems:
1. the simulator is a bad state: the application bundle is installed, but is not visible to Springboard or simctl.
2. the CoreSimulatorService is in a bad state and needs to be reset.
This PR attempts to address second possibility.  If simctl fails to launch the app (times out), #launch will restart the CoreSimulatorService.
=> CoreSim#launch: improve retrying

scripts/run_loop_host.js
Found this while running pre2 and pre3. Happy to write a test for the change but the test suite is pretty daunting and I could use a nudge in the right direction.
=> Fixing syntax error in host script

lib/run_loop/xcuitest.rb
Stand up a end-to-end cucumber test in DeviceAgent.
=> XCUITest can perform queries by id

lib/run_loop/environment.rb, spec/lib/environment_spec.rb
Improves windows env detection based on some sample code I found in rubygems gem.
=> Env: improved windows env detection

Gemfile, run_loop.gemspec
This is the last version that supports ruby < 2.2
=> Gem: pin listen to 3.0.9

lib/run_loop/detect_aut/xcode.rb, spec/lib/detect_aut/xcode_spec.rb
https://groups.google.com/forum/#!topic/calabash-ios/ejKBE9L-SvU
=> DetectAUT ignores UrbanAirship and Google iOS SDK .xcodeproj

lib/run_loop.rb, lib/run_loop/core.rb, spec/lib/core_spec.rb, spec/lib/run_loop_spec.rb
Resolves **Default UIA strategy is incorrect in run-loop 2.1.1** #450
=> Fix :script and :uia_strategy detection

lib/run_loop/xcuitest.rb
More gestures for the DeviceAgent.
=> XCUITest: progress on gesture API

scripts/lib/on_alert.js
* Spanish es, es-419, es-MX, es-US
* Dutch
* German
* Fix French localization
* Danish
=> Add more localizations for privacy alerts

lib/run_loop/core_simulator.rb, lib/run_loop/detect_aut/xcode.rb, lib/run_loop/device.rb, lib/run_loop/host_cache.rb, lib/run_loop/sim_control.rb, spec/lib/host_cache_spec.rb
HOME cannot be expanded in some cases.
Fixes **~/ cannot be expanded in some cases - for example RubyMine** #470 
Thanks @TeresaP for reporting.
=> Replace ~/ with Environment.user_home_directory

lib/run_loop/xcuitest.rb
Progress on:
* [JIRA: DeviceAgent - text entry](https://xamarin.atlassian.net/browse/TCFW-32)
* [JIRA: run-loop 2.1.4](https://xamarin.atlassian.net/browse/TCFW-30)
* [JIRA: DeviceAgent action layer for Calabash](https://xamarin.atlassian.net/browse/TCFW-31)
=> XCUITest: support text entry

lib/run_loop/core.rb, spec/integration/core_spec.rb, spec/lib/core_spec.rb
UIAutomation is not available on Xcode 8.
Xcode 8.0b3 is now installed on Jenkins.
=> Core.default_tracetemplate raises on Xcode 8

lib/run_loop/xcuitest.rb
Progress on:
* Calabash iOS: implement pan with DeviceAgent [JIRA](https://xamarin.atlassian.net/browse/TCFW-243)
=> XCUITest: add #pan_between_coordinates

lib/run_loop/device_agent/client.rb, lib/run_loop/http/retriable_client.rb, spec/lib/device_agent/client_spec.rb, spec/lib/http/retriable_client_spec.rb
Now that Xcode GM is out, we will start cutting pre-releases.
This PR moves the Client closer to being production ready by improving the HTTP interactions with DeviceAgent locally on the Xamarin Test Cloud.
=> Improve DeviceAgent::Client HTTP interactions

lib/run_loop/device_agent/client.rb
Reformatting `tree` output to have all elements in one dimension array.
=> Flat_tree method

lib/run_loop/device_agent/client.rb, spec/lib/device_agent/client_spec.rb, spec/resources.rb, spec/resources/device-agent-tree/preferences.json
Added an example and refactored method names, variables, and arguments.
ATTN: @ark-konopacki Thanks for doing this!  Saved me a lot of time.
=> Client: move flatten_tree to private methods

lib/run_loop/device_agent/client.rb
Progress on:
* Expose DeviceAgent.clear_text as public method [#1168](https://github.com/calabash/calabash-ios/issues/1168)
=> Adds clear text for device agent

lib/run_loop/device_agent/client.rb
Forward launch options to CoreSimulator
=> Forward launch options to CoreSimulator

lib/run_loop/core.rb, lib/run_loop/xcode.rb, spec/integration/core_spec.rb, spec/lib/core_spec.rb, spec/lib/xcode_spec.rb
Xcode 8.2 beta 2 is out.  Expecting a release next week.
=> Support Xcode 8.2

lib/run_loop/core_simulator.rb, spec/integration/core_simulator_spec.rb, spec/lib/core_simulator_spec.rb
UITest has stopped quitting the simulator by default at every launch and the results have been good.
=> CoreSim: quit simulator only when necessary

lib/run_loop/device.rb
Dramatically reduces the amount of time spent waiting for simulators to become stable.
=> Device: improve the wait-for-simulator-stable algorithm

scripts/lib/on_alert.js
* Swedish localization for privacy alerts [TCFW-947](https://jira.xamarin.com/browse/TCFW-947)
* Add nl_BE localizations to Dutch privacy alerts [TFCW-922](https://jira.xamarin.com/browse/TCFW-922)
=> Add nl_BE and Swedish localizations for privacy alerts

lib/run_loop/device_agent/client.rb
The previous implementation always return `false`.  Now that the simulator is not restarted by default, it is possible that the running DeviceAgent will be stale and require a shutdown and a reinstall.
=> DeviceAgent#Client: check if running DeviceAgent is stale

lib/run_loop/device_agent/client.rb
The timeout for entering text should scale with the length of the text that is input.
=> DA:Client: use a separate timeout for entering text

lib/run_loop/core_simulator.rb
Completes:
* run-loop: CoreSim.app_installed? needs update for Xcode 9 [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/19808)
=> Xcode 9: Update CoreSim.app_installed?

lib/run_loop/core.rb, lib/run_loop/device.rb, lib/run_loop/xcode.rb, spec/integration/device_spec.rb, spec/lib/core_spec.rb, spec/lib/xcode_spec.rb, spec/resources.rb
=> Gem: add Xcode 9.3 support

lib/run_loop/core.rb, lib/run_loop/xcode.rb, spec/lib/core_spec.rb, spec/lib/xcode_spec.rb
=> Add support for Xcode 9.4

lib/run_loop/simctl.rb, spec/lib/simctl_spec.rb
Starting in Xcode 10 betas, simctl install can fail with 'This app could not be installed at this time' error.
Retrying the install works.
Progress on:
* Xcode 10: iOSDeviceManager all simulator rspec tests are failing on beta 6 [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/45651)
=> Simctl: retry app install on 'could not install app at this time' error

azure-pipelines.yml, lib/run_loop/core_simulator.rb, lib/run_loop/xcode.rb, scripts/ci/jenkins/test/integration.sh, spec/integration/core_simulator_spec.rb, spec/lib/xcode_spec.rb
The Jenkins instance has been retired.
I am working on standing up a public organization to host the pipelines.
=> Set up CI with Azure Pipelines

azure-pipelines.yml
Progress on this feature:
* Move the Xamarin.UITest dependencies CI/CD from Jenkins to Azure DevOps pipelines [ADO](https://dev.azure.com/msmobilecenter/PM/_workitems/edit/61629)
=> ADO: create an Xcode / macOS test matrix

spec/resources.rb
We've fixed spec tests to detect Xcode's in the `/Users/Shared/Xcode` folder
=> Detect new Xcode location

azure-pipelines.yml
Include Xcode 11 + Mojave step to RunLoop CI
=> Add Xcode 11 to CI

lib/run_loop/environment.rb, spec/lib/environment_spec.rb
Define Azure Pipelines as CI system
=> Define Azure Pipelines as CI system

azure-pipelines.yml
=> add Xcode 11.1 and Xcode 11.2 to the test matrix

Rakefile
In this PR we have split DeviceAgent and iOSDeviceManager rake tasks.
Also we have fixed incorrect logic that was in `device_agent:clean` task before
=> Split DeviceAgent and iOSDeviceManager tasks

lib/run_loop/core_simulator.rb
This was added to be able to perform the actions on the main screen and the notifications area as well which is controlled by the Springboard.app from the CoreServices folder.
`
RunLoop.run(bundle_id: 'com.apple.springboard')
device_agent.touch(id: 'Calendar')
`
=> Added looking into system services dir for the apps to run

lib/run_loop/device_agent/client.rb
Allow one more new query key 'descendant_element'
=> [Support] Add new descendant query

CHANGELOG.md, lib/run_loop/device.rb, lib/run_loop/xcode.rb
installd is no longer there in the first run, removing it from the xcode 12 list
=> Fix Xcode12 bootstrap
