calabash/run_loop

lib/run_loop/lipo.rb
spec/lib/lipo_spec.rb

**run-loop's lipo compatibility check is raising an error when it can't parse -info output without any helpful information** [#656](https://github.com/calabash/calabash-ios/issues/656)
@krukow This compatibility check is new in 0.12.0.  I know you don't like raise exceptions, but if this condition occurs, we _will_ throw an exception downstream [lipo.rb:L71](https://github.com/calabash/run_loop/blob/develop/lib/run_loop/lipo.rb#L71).  If we raise here, at least we'll get more information about the output of `lipo -info`.

Lipo compatibility check should raise an exception with a verbose message

---

lib/run_loop/lipo.rb

Prevents error if path contains space characters.
Cheers.

Escape binary path in argument to lipo.

---

lib/run_loop/version.rb
spec/lib/version_spec.rb

Issue #110 
0.12.0 should be bigger (>) than 0.12.0.pre2

Fix stable and pre-release comparison

---

lib/run_loop/core.rb
spec/lib/core_spec.rb

Was iPhone 5. Xcode 6's default simulator is iPhone 5s. This is an attempt to improve the first-run experience by avoiding the binary-is-incompatible-with-simulator problem.
* https://github.com/calabash/run_loop/blob/develop/lib/run_loop/lipo.rb#L25
* **Ensure compatible arch before launching on device** #80

Use iPhone 5s as simulator default

---

run_loop.gemspec

We temporarily had to pin version to 1.8.1.

Relax json dependency to ~> 1.8

---

lib/run_loop/version.rb
scripts/run_loop_host.js

Fix https://github.com/calabash/calabash-ios/issues/670 by using a small delay causing instrument to flush log buffer

Introduce a delay which causes instruments to flush log output

---

lib/run_loop.rb
lib/run_loop/environment.rb
lib/run_loop/host_cache.rb
spec/lib/environment_spec.rb
spec/lib/host_cache_spec.rb

* **In multi-user environments, /tmp/run_loop_host_cache causes permissions issues** #121
The cache file will be written to a user-specific directory.  I opted to use the `uid` of the user because:
* `ENV['USER']` could be empty
* `whoami` can return user names with spaces, invalid path characters, and UTF8 characters.

Namespace the run-loop cache dir - Fix for

---

run_loop.gemspec

* **version 1.0.0 `stub_env` is raising {} does not implement: stubbed?** [#1](https://github.com/littleowllabs/stub_env/issues/1)

stub_env version 1.0.0 is broken

---

lib/run_loop.rb
lib/run_loop/process_waiter.rb
spec/integration/process_waiter_spec.rb
spec/lib/process_waiter_spec.rb

The simctl API and dylib API needs to do a lot of waiting for processes to start and processes to stop.
Can be merged after CI passes.

ProcessWaiter to wait for processes

---

scripts/calabash_script_uia.js

Corresponds to CalabashScript update:
https://github.com/krukow/calabash-script/commit/6e4207dbdabebfbaa48decd2bdb3e6928887e6e7
Ruby API. You call `uia.selectPickerValues` via Calabash's `uia`. `uia.selectPickerValues` takes a map of `index -> desiredValue` (not desired value always seems to be a string).
Samples:
```ruby
uia(%Q[uia.selectPickerValues('{0 "5"}')])
uia(%Q[uia.selectPickerValues('{0 "3" 1 "59" 2 "PM"}')])
uia(%Q[uia.selectPickerValues('{0 "April" 2 "2017"}')])
```

Support pickers

---

lib/run_loop/sim_control.rb

A minor change that I want to run through CI.
I think we should be avoiding 'sh' when spawn processes.

Avoid shelling out in popen3 call to simctl erase

---

lib/run_loop/lldb.rb
lib/run_loop/process_waiter.rb
spec/integration/lldb_spec.rb
spec/integration/process_waiter_spec.rb
spec/lib/lldb_spec.rb
spec/resources.rb

LLDB tests are flickering on Travis; disabled them after an analysis.  lldb is refusing to start for > 10 seconds.
Replaced integration test for kill_lldb_processes with a mocked unit test.

Stablize lldb examples

---

lib/run_loop/core.rb
lib/run_loop/instruments.rb
spec/lib/core_spec.rb

We need to get away from accessing this variable directly.
In the gem, use `RunLoop::Environment.debug?`.
In rspec tests, use `stub_env('DEBUG', < new value >)`.  In the rspec tests, you can wrap specs in a `Resources.share.with_debugging {}` to enable a debug mode in the context of the block.

Replace ENV['DEBUG'] calls

---

lib/run_loop/sim_control.rb

Fixes **SimControl is not filtering by "(unavailable, runtime profile not found)" causing failing builds when Xcode betas are installed** #137
Possibly related to:  **Simulator not found under Xcode 6.3 beta 2 using RESET_BETWEEN_SCENARIOS=1** [#724](https://github.com/calabash/calabash-ios/issues/724)

FIX: #137 simctl should filter unavailable devices

---

lib/run_loop/core.rb
lib/run_loop/environment.rb
lib/run_loop/xctools.rb
spec/integration/core_spec.rb
spec/lib/core_spec.rb
spec/lib/environment_spec.rb

We should stop accessing environment variables directly with ENV.
* TRACE_TEMPLATE needs to be in Environment #141

Move ENV vars to environment.rb

---

.travis.yml

Email is drag.  I use a Unix Terminal + Growl to keep an eye on Travis.
Let's try Slack?
Will post Travis CI notifications to the #calabash channel.

Add slack notifications for travis

---

lib/run_loop/core.rb
spec/integration/run_sim_spec.rb
spec/lib/core_spec.rb

Fixes: **setting DEVICE_TARGET to a simulator UDID causes crash**  [#714](https://github.com/calabash/calabash-ios/issues/714)

Can use simulator UDID for DEVICE_TARGET

---

lib/run_loop/xctools.rb
spec/lib/xctools_spec.rb

Xcode 6.3 betas are expanding to `Xcode-beta.app`, not `Xcode-Beta.app`.

Detect Xcode-beta.app (new in Xcode 6.3 beta 3)

---

lib/run_loop/host_cache.rb
spec/lib/host_cache_spec.rb

We parallelize work by running multiple instances on different user accounts on the same Mac. By having a folder structure under /tmp, there is permissions collision based on which instance creates the parent folder. This PR proposes a flat folder structure under /tmp per uid to avoid this issue.

Avoid permission collision of parent temp folder when running multiple instances from different user accounts on the same machine

---

lib/run_loop/simctl/bridge.rb
spec/integration/simctl/bridge_spec.rb

Two items:
1. **Xcode 6.3 - instruments cannot launch an app that is already installed on iOS 8.3 Simulators** https://github.com/calabash/calabash-ios/issues/744
2. run-loop should provide a way to uninstall an app to avoid stale binaries
@rasmuskl @acroos @john7doe

simctl bridge can uninstall an app

---

lib/run_loop/simctl/bridge.rb
spec/integration/simctl/bridge_spec.rb
spec/lib/simctl/bridge_spec.rb

Cleaned up the Simctl::Bridge implementation so it can be used in releases.
Two items:
1. **Xcode 6.3 - instruments cannot launch an app that is already installed on iOS 8.3 Simulators** https://github.com/calabash/calabash-ios/issues/744
2. run-loop should provide a way to uninstall an app to avoid stale binaries
@rasmuskl @acroos @john7doe

Make simctl bridge production ready

---

.travis.yml
lib/run_loop/core.rb
lib/run_loop/environment.rb
lib/run_loop/process_waiter.rb
lib/run_loop/sim_control.rb
lib/run_loop/simctl/bridge.rb
spec/integration/simctl/bridge_spec.rb
spec/lib/environment_spec.rb

Two items:
1. **Xcode 6.3 - instruments cannot launch an app that is already installed on iOS 8.3 Simulators** https://github.com/calabash/calabash-ios/issues/744
2. run-loop should provide a way to uninstall an app to avoid stale binaries
@rasmuskl @acroos @john7doe 
cc @krukow 
I tested with the WebView and SmokeApp against Xcode 6.3:
* iOS 8.3
* iOS 8.2
* iOS 8.1
* iOS 7.1
iOS 7.0.3 does not launch on Yosemite (known limitation).

Implement fix for Xcode 6.3 + iOS 8.3 simulators

---

lib/run_loop/patches/retriable.rb

Fixes [**retriable should support older versions**](https://github.com/calabash/calabash-ios/issues/748)
The problem is that the retriable _require path_ for 1.3.3.1 and 2.* _includes_ version.rb.  This is not the case for retriable 1.4.1 - I am not sure when the change actually occurred.
cc @krukow @nishanil
(>_>)

Retriable patch needs to retriable/version

---

run_loop.gemspec

http://guides.rubygems.org/patterns/
At its core, RubyGems exists to help you manage Ruby’s $LOAD_PATH, which is how the require statement picks up new code. There’s several things you can do to make sure you’re loading code the right way.
**Respect the global load path**
When packaging your gem files, you need to be careful of what is in your lib directory. Every gem you have installed gets its lib directory appended onto your $LOAD_PATH. This means any file on the top level of the lib directory could get required.
**Mangling the load path**
Gems should not change the $LOAD_PATH variable. RubyGems manages this for you. Code like this should not be necessary:
```
lp = File.expand_path(File.dirname(__FILE__))
unless $LOAD_PATH.include?(lp)
$LOAD_PATH.unshift(lp)
end
```
Or:
```
__DIR__ = …
```

Remove LOAD_PATH shifting; it is unnecessary

---

lib/run_loop/simctl/bridge.rb

Xamarin Studio uses a `csproxy` process to interact with the CoreSimulatorBridge.framework.
This is the parent process of the processes launched by Xamarin's interaction with CoreSimulatorBridge.
I recently ended up with a bunch of orphaned processes after force quitting Xamarin Studio.  The intent here is to kill the parent `csproxy` if it is running.

Simctl::Bridge should manage Xamarin's csproxy

---

lib/run_loop/device.rb
lib/run_loop/xctools.rb
spec/lib/device_spec.rb

Calabash 2.0 needs a convenient API for finding a device or simulator with a given name.

Add Device.device_with_identifer method

---

.travis.yml
Rakefile
scripts/ci/travis/rspec-ci.rb
spec/lib/instruments_spec.rb

iOS Simulators on Travis are just not stable enough.

Travis CI: disable any test that starts a simulator

---

run_loop.gemspec

Follow up on **Remove LOAD_PATH shifting; it is unnecessary** #179
Our current solution works, but in CI where run_loop is built repeatedly you see:
```
/Users/travis/.rvm/gems/ruby-2.0.0-p481/bundler/gems/run_loop-4cfee2256809/lib/run_loop/version.rb:2: warning: already initialized constant RunLoop::VERSION
/Users/travis/build/calabash/calabash-ios-server/calabash-ios/run_loop/lib/run_loop/version.rb:2: warning: previous definition of VERSION was here
```
This solution also enforces the version patterns outlined in the README.md - 1.2.3 and 1.2.3.pre3

Search for and validate gem version

---

lib/run_loop/sim_control.rb
lib/run_loop/simctl/bridge.rb
spec/integration/sim_control_spec.rb

Each time the simulator launches it steals keyboard focus. This is super distracting when trying to do anything else while the tests run.
From `man open`
-g  Do not bring the application to the foreground.

prevent simulator from stealing focus between scenarios

---

lib/run_loop/core.rb
lib/run_loop/sim_control.rb
lib/run_loop/simctl/bridge.rb
lib/run_loop/xctools.rb
spec/lib/core_spec.rb
spec/lib/sim_control_spec.rb
spec/lib/xctools_spec.rb

Xcode 7 changed the name and location of the iOS Simulator application and changed the name.
Unit tests are passing on Xcode 6 + 7.

Xcode 7 beta support

---

lib/run_loop/core.rb
lib/run_loop/device.rb
spec/lib/app_spec.rb
spec/lib/cli/errors_spec.rb
spec/lib/core_spec.rb
spec/lib/device_spec.rb
spec/lib/lipo_spec.rb
spec/lib/patches/retriable_spec.rb
spec/lib/simctl/bridge_spec.rb

New behavior in rspec 3.3.x - warn if `raise_error` does not specify the error type.
Found two cases where not specifying the error was hiding unexpected behavior.

Expect {} raise_error should specify the error

---

lib/run_loop/xctools.rb

A typo in the test for Xcode 7 causes inability to use Xcode 6.4 with Xcode 7 installed

Fixed typo in xcode 7 check

---

lib/run_loop/xctools.rb
spec/lib/xctools_spec.rb

Using the new `keyboard-language` route proposed in https://github.com/calabash/calabash-ios-server/pull/221, this PR adds a facility in runloop to lookup the localized name of things like buttons and keys:
(RunLoop::XCTools.new).lookup_localization_name('delete.key', 'da') 
=> "Slet"

uikit localization lookups in runloop

---

lib/run_loop/cli/simctl.rb

```
$ run-loop simctl tail
/Users/moody/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/run_loop-1.4.1/lib/run_loop/cli/simctl.rb:19:in `tail_booted': undefined method `simulator_log_file_path' for nil:NilClass (NoMethodError)
```

Fail gracefully when no booted sim is found

---

scripts/run_loop_fast_uia.js
scripts/run_loop_host.js
scripts/run_loop_shared_element.js

The only surprise here is: `["OK", /enviarle notificaiones/]`, which was requested by @GlennWilson (client request).
Resolves: **Privacy dialog: Microphone** #170
Tested with @Oddj0b [Permissions.app](https://github.com/Oddj0b/Permissions) :+1: :pizza: 
Messes with **Feature/refactor onalert javascript** #106  which needs rebasing or updating to handle these changes (@svevang ).

Add more privacy alert auto-dismiss regular expressions

---

lib/run_loop/sim_control.rb

Xcode 7's simctl includes watchOS simulators.

Filter watch simulators out of simctl output

---

lib/run_loop/xctools.rb
spec/lib/xctools_spec.rb

* Xcode 7 includes an en_AU localization
* Match project style
* Prefer `send` vs. `instance_eval` for testing private methods (there are many examples that use `instance_eval`; they should all be changed at some point)
* Prefer constants over class variables
@svevang Sorry that the diff is so cluttered; I had to adjust the indentation of the l10n block in XCTools.

Revise Xcode l10n support

---

lib/run_loop.rb
lib/run_loop/xcode.rb
spec/integration/xcode_spec.rb
spec/lib/xcode_spec.rb

Xcode 7.0's instruments output has changed.
This new Xcode class is designed to take over some of the duties of the XCTools.
The XCTools class will be deprecated and its behaviors divided into three classes:
* Xcode
* Instruments
* L10n

Add an Xcode class

---

README.md
Rakefile
lib/run_loop/core.rb
lib/run_loop/device.rb
lib/run_loop/sim_control.rb
lib/run_loop/simctl/bridge.rb
spec/integration/bin/instruments_spec.rb
spec/integration/bin/simctl_spec.rb
spec/integration/dylib_injector_spec.rb
spec/integration/instruments_spec.rb
spec/integration/process_terminator_spec.rb
spec/integration/process_waiter_spec.rb
spec/integration/run_loop_spec.rb
spec/integration/sim_control_spec.rb
spec/integration/simctl/bridge_spec.rb
spec/integration/simulator_compatibility_spec.rb
spec/lib/cli/cli_spec.rb
spec/lib/cli/simctl_spec.rb
spec/lib/device_spec.rb
spec/resources.rb

The integration examples have been suffering from bit rot because they are not part of any CI build.
Took the time to see what is and what is not working on Xcode 7 beta 6.
* simctl is broken.
* instruments is broken for simulators.
I did not have time to run on-device tests for Xcode 7 vs. any iOS version.
Discovered/reproduced [**calabash-ios not working with iOS 7.1 Simulators**](http://stackoverflow.com/questions/32313999/calabash-ios-not-working-with-ios-7-1-simulators)

Stabilize integration examples

---

lib/run_loop/core.rb
spec/lib/core_spec.rb

Xcode 7 simulators do not include the word 'Simulator'.

Core.simulator_target? - fixup for Xcode 7

---

lib/run_loop/device.rb
lib/run_loop/life_cycle/core_simulator.rb
spec/lib/device_spec.rb

The first launch of a simulator takes a long time.  This is especially true in iOS 9.
This PR waits for the simulator to install.
Support for: https://github.com/calabash/run_loop/issues/224

CoreSimulator#launch_simulator waits for the simulator to install

---

lib/run_loop/cli/simctl.rb
lib/run_loop/device.rb
lib/run_loop/directory.rb
lib/run_loop/life_cycle/core_simulator.rb

I need a way to ensure that any given CoreSimulator is installed.
Fixes: https://github.com/calabash/run_loop/issues/224 and https://github.com/calabash/run_loop/issues/223
```
$ be run-loop simctl help doctor
Usage:
run-loop doctor
Options:
-v, [--debug], [--no-debug]  # Enable debug logging.
-d, [--device=DEVICE]        # The simulator UDID or name.
EXPERIMENTAL: Prepare the CoreSimulator environment for testing
$ be run-loop simctl doctor
$ be run-loop simctl doctor --device DCFE6D89-C91A-4420-A2C7-CD65E923ACDD
```

CLI: simctl doctor [--device=DEVICE] - tool to prepare CoreSimulator environment

---

lib/run_loop/instruments.rb
lib/run_loop/life_cycle/core_simulator.rb
lib/run_loop/xcrun.rb
run_loop.gemspec
spec/integration/instruments_spec.rb
spec/integration/xcrun_spec.rb
spec/lib/instruments_spec.rb

Progress toward **Pass all `read` calls through utf-8 filter and come up with a way of testing** #230

Force UTF-8 encoding when reading the output of `instruments`

---

lib/run_loop/core.rb
lib/run_loop/simctl/bridge.rb

Xcode 6 instruments will not install an app that is already installed.
This has been a thorn in my side.
```ruby
$ be run-loop instruments launch --app $APP --device $DEVICE --debug
2015-09-11 08:17:02 +0200 [RunLoop:debug]: Simulator instruction set 'x86_64' is compatible with ["i386", "x86_64"]
/Users/moody/git/calabash/run-loop/lib/run_loop/core.rb:157:in `prepare_simulator':  (RuntimeError)
The app you are trying to launch is not the same as the app that is installed.
Installed app SHA: 61fe407c4a6b334d88753c4dc148f24e54b21c8d3b7c02961cc7c2257698a2fb
App to launch SHA: 2472f284d401664a69fa6804e409cc2ed3214c887e23cf8e4a83741868f2a367
You can ensure that you are testing the correct .app by running:
$ run-loop simctl --app "/Users/moody/git/calabash/ios-smoke-test-app/CalSmokeApp/CalSmoke …
```

Core.prepare_simulator raise an error if the installed app is stale

---

lib/run_loop/core.rb
spec/lib/core_spec.rb

**Core.prepare_simulator should raise an error if the app does not exist.** #233
* Moved the arch compatibility check into Core.prepare_simulator
* Deprecated (public) Core.expect_simulator_compatible_arch
* Added (private) Core.expect_simulator_compatible_arch

Core.prepare_simulator raises an error if app does not exist

---

lib/run_loop/core.rb
lib/run_loop/life_cycle/core_simulator.rb

Fixes **Install new app if installed app SHA is different** #241
1. Does nothing if the app is not installed.
2. Does nothing if the app the same as the app that is installed
3. Installs app if it is different from the installed app
Only the app is uninstalled; the app sandbox is preserved.
This strategy respects the user's wishes by _not resetting the app sandbox unless they ask us to_.
Finally.
Big thanks to @rasmuskl for finding the magic plist.
* **In CoreSimulator environments RESET_BETWEEN_SCENARIOS=1 resets the simulator contents and settings; should only reset the app sandbox** [#597](https://github.com/calabash/calabash-ios/issues/597)
* **Fix reset btw scenarios xcode 6** [#526](https://github.com/calabash/calabash-ios/pull/526)

Use CoreSimulator to ensure target app is the same as installed app

---

CHANGELOG.md
lib/run_loop/core.rb
lib/run_loop/version.rb
lib/run_loop/xctools.rb

Thanks to @ark-konopacki for reporting.
**Cannot run tests with Calabash 0.14.3 and run_loop 1.5.2** [#843](https://github.com/calabash/calabash-ios/issues/843)

HOTFIX: backward compatibility for Calabash < 0.16.1 

---

lib/run_loop/life_cycle/core_simulator.rb
spec/lib/life_cycle/core_simulator_spec.rb

Removes LaunchServices-134.csstore when resetting sandbox. 
Filename is hardcoded in the same vein as [UITest] (https://github.com/xamarin/Xamarin.UITest/blob/1e3dbc480b430b76da9c7ec2576527b3a83ff51f/src/Xamarin.UITest.Shared/iOS/iOSSimulatorManagement.cs#L107).

rm LaunchServices-134.csstore

---

lib/run_loop/core.rb
spec/integration/core_spec.rb
spec/lib/core_spec.rb
spec/resources.rb

`Core.simulator_target?` was not match simulators created with `xcrun simctl create`.

Core.simulator_target? should match simulators created by users

---

lib/run_loop/xcrun.rb
spec/lib/xcrun_spec.rb

The previous default of 10s was too short for older machines and CI environments.
**Default timeout in instruments.rb causes failure on slow hardware** #259

Increase the default timeout for Xcrun.exec

---

lib/run_loop/instruments.rb
spec/lib/instruments_spec.rb

**Default timeout in instruments.rb causes failure on slow hardware** #259
It is not necessary to call `instruments` to get its version.
```
def timeit
Benchmark.realtime do
10.times do
RunLoop::Instruments.new.version
end
end
end
> timeit => ~5.0s
> timeit => ~0.1s
```

Instruments#version extracts version from Instruments.app Info.plist

---

run_loop.gemspec

**Ruby files glob in gemspec should match **/*.rb not **/*** #260

Gem: ruby_files glob should catch only ruby files

---

.travis.yml
lib/run_loop/xcrun.rb
run_loop.gemspec
spec/lib/xcrun_spec.rb
spec/spec_helper.rb

We want to use command_runner_ng, but it does not support ruby 1.9.3.
Pending support for ruby 1.9.3, this is a patch for Xcrun#exec.
**Add support for ruby 1.9** [#5](https://github.com/kamstrup/command_runner_ng/pull/5)

Add ruby 1.9 support for Xcrun#exec

---

lib/run_loop/life_cycle/simulator.rb

Generated by iproxy, this can bind port 37265 and prevent the server from starting.
**run-loop needs to manage iproxy process** #277

Simulator: should manage the 'iproxy' process

---

lib/run_loop/version.rb
spec/lib/version_spec.rb

**Xcode 7.1 beta 2: instruments and simctl need to filter out Apple TV from known simulators** #283
Might have some downstream consequences, but I doubt it.  We'll run this through CI a bunch before a release.

Version can be used as hash key

---

lib/run_loop/device.rb
lib/run_loop/directory.rb
spec/lib/directory_spec.rb

**R&D: Found an instruments stdio.pipe in CoreSimulator** #245
Users are reporting Xcrun timeout with 'du'.  The problem is that occasionally the simulator directories contain pipes (instruments.stdpipe) which cause 'du' to block.
Adds Directory.size method that skips non-standard files to avoid blocking.

Fix 'du' is blocking problem with Directory.size

---

lib/run_loop/device.rb
lib/run_loop/directory.rb

While doing some debugging on other issues, I discovered that Device was logging ignorable errors that should have been logged in Directory.directory_digest.

Improve Directory.directory_digest and Device#simulator_wait_for_stable_state interaction

---

lib/run_loop/environment.rb
spec/lib/environment_spec.rb

On the XTC we don't want to be writing to a home directory which might be shared.

Environment: user home on XTC is ./tmp/home

---

lib/run_loop/dot_dir.rb
spec/lib/dot_dir_spec.rb

There was some unused code left over from an attempt at rotating instruments caches.

DotDir: remove unnecessary code

---

lib/run_loop/core.rb
lib/run_loop/instruments.rb
lib/run_loop/logging.rb
spec/lib/instruments_spec.rb
spec/lib/logging_spec.rb

Each Calabash generates a >= 25 M directory in /Library/Cache/com.app.dt.instruments.
Run loop will now rotate these directories keeping only the 5 most recent.  On the XTC the rotate step does nothing.
Fixes **Running out of disk space because of cached instruments files** #276
Initially, I implemented the rotate in a forked process because the first run will take a long time to complete - it will possibly have to delete hundreds of _gigabytes_ of files. Subsequent runs will be fast; any delays will be lost in the noise of launching the simulator. Instead of the async solution, I added non-optional logging if a large number of directories is discovered.  This logging explains what is happening, asks the user to be patient, and shows progress.  I kept the commits for the async solution …

Rotate /Library/Cache/com.app.dt.instruments directories

---

lib/run_loop/environment.rb
spec/lib/environment_spec.rb

Fixes **Expand APP (and APP_BUNDLE_PATH) path before launching instruments** #255
Instruments cannot handle relative paths or paths with "~/"

Environment: expand the APP bundle path

---

lib/run_loop/dylib_injector.rb
scripts/ci/jenkins/rspec-unit.sh
spec/integration/dylib_injector_spec.rb
spec/lib/dylib_injector_spec.rb

Fixes:
* **lldb can hang indefinitely when injecting dylib** #264
* **Could not inject dylib (RuntimeError)** #301
Progress on:
* **remove Retriable from the gem** #310
* **Integration examples need attention** #243
Thanks @MortenGregersen for reporting.
Disabled the integration test on Jenkins.  I need to see the UI and screensharing is off for some reason.

Improve dylib injection for simulators

---

lib/run_loop/lldb.rb
spec/lib/lldb_spec.rb

**Improve dylib injection for simulators** #311 improved our interactions with lldb.
I don't think the TERM is necessary anymore and we were waiting too long for lldb to die.

Send KILL to lldb directly and don't wait as long for lldb to die

---

.travis.yml
lib/run_loop/core_simulator.rb
scripts/ci/jenkins/rspec-unit.sh
spec/integration/core_simulator_spec.rb
spec/lib/core_simulator_spec.rb

If an an app is already installed (the SHAs match) CoreSimulator#install will not launch the simulator.
In that case, CoreSimulator#launch was not launching the simulator before trying to install which cased install errors.
CoreSimulator#launch_simulator and the CoreSimulator class now manage launching using a class variable `@@simulator_pid` - this might fix the double-launching issues some users have reported.

CoreSimulator#launch launches simulator even if app is installed

---

lib/run_loop/device.rb
lib/run_loop/xcrun.rb

Progress on:
**RunLoop::Directory.directory_digest does not complete on slower machines** #307
Some users are reporting Xcrun is timing out.
@xinsight is reporting that Directory.directory_digest is _logging a warning_ - no error is raised.
This PR exposes the options that control `Xcrun#exec` and `Device#simulator_wait_for_stable_state` to users.
For cucumber users, the best place to override would be in your features/support/env.rb.
```
RunLoop::Xcrun::DEFAULT_OPTIONS[:timeout] = 60
RunLoop::Device::SIM_STABLE_STATE_OPTIONS[:timeout] = 60
```

Expose important timeouts as constant mutable variables

---

lib/run_loop/directory.rb
spec/lib/directory_spec.rb

The existing message looks like an error.  It is an error, but it is completely ignorable.
Resolved:
**RunLoop::Directory.directory_digest does not complete on slower machines** #307

Directory: better logging of digest read errors

---

.travis.yml
lib/run_loop/sim_control.rb
spec/integration/detect_simulators_spec.rb
spec/lib/sim_control_spec.rb

Resolves:
* Xcode 7.1 - SimControl is not finding iOS 9.0 simulators #318
Added an integration example to Travis.
Progress on:
* Integration examples need attention #243

Simplify the detection of iOS Simulator

---

lib/run_loop/core_simulator.rb
lib/run_loop/device.rb
lib/run_loop/environment.rb
spec/lib/core_simulator_spec.rb
spec/lib/environment_spec.rb

Calabash Jenkins CI is up and running again.  It is now running on El Capitan.  I noticed that in CI environments the defaults for:
* simctl install app
* simctl launch app
* the simulator stable state
were too low; sometimes raising errors.
Run-loop now tries to detect CI environments.  When it does, it significantly increases the CoreSimulator related timeouts.
In addition, users can control the following RunLoop::CoreSimulator::OPTIONS:
```
:install_app_timeout => RunLoop::Environment.ci? ? 60 : 30,
:app_launch_timeout => RunLoop::Environment.ci? ? 60 : 30
```
Progress on:
**Collect information about Calabash sessions** [#908](https://github.com/calabash/calabash-ios/issues/908) - detecting CI environments is a requirement.

Increase simctl install/launch app and simulator stable timeouts in CI environments

---

lib/run_loop/device.rb
lib/run_loop/directory.rb
spec/lib/directory_spec.rb

Refines:
* **Directory: better logging of digest read errors** #316
* **RunLoop::Directory.directory_digest does not complete on slower machines** #307

Improve Directory.directory_digest response to File.read errors

---

lib/run_loop/core_simulator.rb
spec/lib/core_simulator_spec.rb
spec/lib/device_spec.rb

Expands upon **Increase simctl install/launch app and simulator stable timeouts in CI environments** #329 by:
* applying uniform naming for default keys
* adding uninstall
Users can override these values in there features/support/env.rb
```
RunLoop::Device::SIM_STABLE_STATE_OPTIONS[:timeout] = 60
RunLoop::CoreSimulator::DEFAULT_OPTIONS[:install_app_timeout] = 30
RunLoop::CoreSimulator::DEFAULT_OPTIONS[:uninstall_app_timeout] = 30
RunLoop::CoreSimulator::DEFAULT_OPTIONS[:launch_app_timeout] = 30
```
RunLoop will try to detect CI environments and automatically increase the timeouts.
Progress on:
* **Collect information about Calabash sessions** [#908](https://github.com/calabash/calabash-ios/issues/908) - detecting CI environments is a requirement.
* **Integration examples need attention** …

Increase simctl and sim stable timeouts in CI environments and expose options to users

---

lib/run_loop/cli/simctl.rb
scripts/ci/jenkins/cli.sh
scripts/ci/jenkins/run.sh

Fixes **command line tool has a reference to Lifecycle module** #332 
On El Capitan, it has been demonstrated that the CoreSimulatorService daemon can become unstable after it has been running for a long time.  This PR improves the:
```
$ bundle exec run-loop simctl manage-processes
```
tool by directing it to KILL the CoreSimulatorService daemon.
If you are seeing FIFO errors in CI (or even locally), try integrating this command into your workflow.
Please note that the service takes a long time (seconds) to restart so don't call this obsessively.

Fix 'simctl manage processes'

---

lib/run_loop/core.rb
scripts/ci/jenkins/run.sh

**RESET_APP_BETWEEN_SCENARIOS is still resetting the simulator not just the app sandbox** [#878](https://github.com/calabash/calabash-ios/issues/878)
Calabash is responsible for sending :reset based on user input and environment variables.  :reset is supported because it is a legacy key.  :reset_app_sandbox is the preferred key.

Core: prepare simulator responds to :reset launch arg

---

lib/run_loop/core_simulator.rb
spec/integration/core_simulator_spec.rb
spec/lib/core_simulator_spec.rb

This is a replacement for SimControl.reset_content_and_settings.
Progress on:
* Deprecate SimControl #320
* need interface to simctl tool #293
* Instruments error inside run_loop when RESET_BETWEEN_SCENARIOS=1 #325
* RESET_APP_BETWEEN_SCENARIOS is still resetting the simulator not just the app sandbox [#878](https://github.com/calabash/calabash-ios/issues/878)

CoreSimulator can erase a simulator

---

lib/run_loop/core_simulator.rb
spec/lib/core_simulator_spec.rb

Fixes timeouts while waiting for Shutdown state while trying to reset the app sandbox.
Progress on:
* Instruments error inside run_loop when RESET_BETWEEN_SCENARIOS=1 #325
* RESET_APP_BETWEEN_SCENARIOS is still resetting the simulator not just the app sandbox [#878](https://github.com/calabash/calabash-ios/issues/878)

CoreSim: expose :wait_for_state_timeout option

---

lib/run_loop/core.rb

There was an order of operations problem.  If the app was not installed, CoreSimulator launched the simulator and installed it (new behavior in Xcode 7).  Then the "enable accessibility" and "enable software keyboard" code would quit the simulator.  And then CoreSimulator would launch the simulator.
I really goofed on this.  Apologies to everyone.

Core: prevent double launching of simulator

---

scripts/run_loop_fast_uia.js
scripts/run_loop_host.js
scripts/run_loop_shared_element.js

Resolves **Dutch APNS dialog is not automatically dismissed** #337
Cannot add to Permissions app because the app is not configured for APNS.
* **Needs to generate Apple Push Notification Services alerts** [#9](https://github.com/calabash/Permissions/issues/9)
I did confirm visually that run-loop can dismiss English APNS alerts in iOS 9.

Privacy: automatically dismiss Dutch APNS alerts

---

lib/run_loop/core.rb

Progress on **`console_attach` needs some love; run-loop should cache runtime info for all strategies** [#828](https://github.com/calabash/calabash-ios/issues/828)
It turns out that we can use this cache for _all_ strategies.
At some point we will need to clarify the name:
* Rename HostCache to RunLoop::Cache #356

HostCache can be used by `console_attach` for all strategies

---

scripts/lib/on_alert.js

Progress on:
* **Ideas for dismissing Privacy alerts** #350
* run-loop 2.0.2
This will allow us to quickly see where we have support gaps.
* Locally with the Permission.app on iOS simulators
* [XTC against iOS 9 devices](https://testcloud.xamarin.com/test/permissions_506622d0-c117-477c-9148-4d3edd9ab550/)
* [XTC against iOS 7 - 9 devices](https://testcloud.xamarin.com/test/permissions_73baf599-8e84-44eb-893e-9900faf8b855/)
ATTN: @krukow No regexes were added.
Thanks @BAJ- for the JavaScript help.

OnAlert: divide regexes by language

---

scripts/lib/on_alert.js

* **No french localization for handling system dialogs like permissions** #369
* **run-loop: release - version TBD** [#93](https://github.com/xamarinhq/test-cloud-frameworks/issues/93)

JS: French localizations for privacy alerts

---

lib/run_loop/cli/cli.rb
lib/run_loop/cli/locale.rb
scripts/lib/on_alert.js
scripts/localizations.rb
spec/lib/cli/locale_spec.rb

I did this work in the context of:
* **No french localization for handling system dialogs like permissions** #369
* **run-loop: release - version TBD** [#93](https://github.com/xamarinhq/test-cloud-frameworks/issues/93)
Progress on **Ideas for dismissing Privacy alerts** #350.
@krukow You need to sign off on this because these changes remove a (perhaps) crucial log statement.  See the code comments.
I added a command line tool to dump the regular expression so they can be easily transferred to other systems.
```
$ be run-loop locale print-alert-regexes
```
These changes have been tested on the XTC.
* https://testcloud.xamarin.com/app/946807a0-8a14-4285-9f82-31fe8c22af40/master

Refactor auto dismiss JavaScript methods

---

lib/run_loop/xcode.rb
spec/lib/l10n_spec.rb
spec/lib/xcode_spec.rb

Resolves **Xcode developer_dir should check if the path exists and fail fast** #371

Raise error if Xcode#developer_dir path does not exist

---

lib/run_loop/app.rb
lib/run_loop/ipa.rb
spec/lib/app_spec.rb
spec/lib/ipa_spec.rb

Progress on **0.18.1 Cannot automatically detect .app** [#1008](https://github.com/calabash/calabash-ios/issues/1008)
We should not have to call out to Lipo directly.

App and Ipa can return arches

---

lib/run_loop/app.rb
spec/lib/app_spec.rb

Progress on **0.18.1 Cannot automatically detect .app** [#1008](https://github.com/calabash/calabash-ios/issues/1008)
We need a way of filtering .apps by simulator bundles.

App: can report if was built for sim or device

---

lib/run_loop/app.rb
spec/lib/app_spec.rb

See: 5ff7036 
The original implementation relied on regular expressions on the _path_ which in hindsight I see can lead to false positives in the `#skip_executable_check?` method which in turn cases the `#calabash_server_version` method to fail which then cause the automatic app detection algorithm to fail.
Resolves:
* App: should skip font files when collecting executables #397
* App: fix the regex for CoreData assets and include missing assets #398
* App: replace the /storyboard/ regex with a basename check #399
Thanks @topgenorth for the machine time!

App: improve exectuable detection in app bundles

---

lib/run_loop.rb
lib/run_loop/app.rb
lib/run_loop/detect_aut/detect.rb
lib/run_loop/detect_aut/errors.rb
lib/run_loop/detect_aut/xamarin_studio.rb
lib/run_loop/detect_aut/xcode.rb
lib/run_loop/environment.rb
spec/lib/detect_aut/detect_spec.rb
spec/lib/detect_aut/errors_spec.rb
spec/lib/detect_aut/xamarin_studio_spec.rb
spec/lib/detect_aut/xcode_spec.rb
spec/lib/environment_spec.rb
spec/resources/detect_aut/DerivedData/ProjectA-00/info.plist
spec/resources/detect_aut/DerivedData/ProjectA-01/info.plist
spec/resources/detect_aut/DerivedData/ProjectA-02/info.plist
spec/resources/detect_aut/DerivedData/ProjectB-00-project/info.plist
spec/resources/detect_aut/DerivedData/ProjectB-00-workspace/info.plist
spec/resources/detect_aut/DerivedData/ProjectB-01-project/info.plist
spec/resources/detect_aut/DerivedData/ProjectB-01-workspace/info.plist
spec/resources/detect_aut/DerivedData/ProjectB-02-project/info.plist
spec/resources/detect_aut/DerivedData/ProjectB-02-workspace/info.plist
spec/resources/detect_aut/DerivedData/ProjectC-00-project/info.plist
spec/resources/detect_aut/DerivedData/ProjectC-00-workspace/info.plist
spec/resources/detect_aut/DerivedData/ProjectC-01-project/info.plist
spec/resources/detect_aut/DerivedData/ProjectC-01-workspace/info.plist
spec/resources/detect_aut/DerivedData/ProjectC-02-project/info.plist
spec/resources/detect_aut/DerivedData/ProjectC-02-workspace/info.plist

Progress on:
* **0.18.1 Cannot automatically detect .app** [#1008](https://github.com/calabash/calabash-ios/issues/1008)
* **Fix automatic detection of .app for simulators** [#148](https://github.com/xamarinhq/test-cloud-frameworks/issues/148)
This is a port of the code from: [launch/simulator_launcher](https://github.com/calabash/calabash-ios/blob/develop/calabash-cucumber/lib/calabash-cucumber/launch/simulator_launcher.rb).  
* Calabash::Cucumber::SimulatorLauncher is going to be removed in 0.19.0
* The app detection code in SimulatorLauncher has been inadequate (broken) for a year or so.
The app is designed so that it can be expanded without too much trouble to handle:
* Detecting .app for arm arches that can then be packaged into .ipas
* Detecting .app for any arch that can then have …

Automatic .app detection

---

lib/run_loop/detect_aut/detect.rb
lib/run_loop/detect_aut/errors.rb
lib/run_loop/detect_aut/xcode.rb
spec/lib/detect_aut/detect_spec.rb
spec/lib/detect_aut/errors_spec.rb
spec/lib/detect_aut/xcode_spec.rb

I did a round of user testing last night and discovered some short falls.
We need to filter out these common .xcodeproj from our Xcode project results:
* CordovaLib
* Pods/Pods.xcodeproj
* Carthage/**/*.xcodeproj
The next obvious step will be to collect _all_ .xcodeproj in the directory and do a search of the resulting DerivedData directories.  There was at least one user with an iOS and MacOS .xcodeproj in their working directory.  We could filter further by asking the .xcodeproj if it has a `osx` target, but I think that might lead to false positives.
Users that receive a `RunLoop::DetectAUT::MultipleXcodeprojError` can set the `XCODEPROJ` env variable to indicate which .xcodeproj they are using.
```
$ XCODEPROCT=MyiOS.xcodeproj be cucumber
```

Improve automatic .app detection

---

lib/run_loop/environment.rb
spec/lib/environment_spec.rb

If these values are `""` we should treat them as nil.

Environment: handle empty strings for DEVICE_TARGET, DEVICE_ENDPOINT, and TRACE_TEMPLATE

---

lib/run_loop/fifo.rb

Some users (myself included) were encountering seemingly random Errno::EPIPE errors around different Calabash gestures which caused tests to fail.  This fixes https://github.com/calabash/run_loop/issues/395.

Flush pipe_io if Errno::EPIPE error is encountered

---

lib/run_loop/core.rb
lib/run_loop/core_simulator.rb
lib/run_loop/device.rb
lib/run_loop/instruments.rb
lib/run_loop/l10n.rb
lib/run_loop/sim_control.rb
lib/run_loop/xcode.rb
scripts/ci/jenkins/run.sh
spec/integration/core_spec.rb
spec/lib/core_simulator_spec.rb
spec/lib/core_spec.rb
spec/lib/device_spec.rb
spec/lib/instruments_spec.rb

Xcode 5 has not been supported for over a year.  Removing these checks makes adding new features easier.

Drop Xcode 5 checks

---

lib/run_loop/core.rb
lib/run_loop/device.rb
spec/lib/device_spec.rb

The responsibility for inferring which device to target is spread across Calabash and RunLoop.  This PR centralizes the rules in the Device class.  The `Device#detect_device` method inspects the launch options and the ENV to determine which device to launch the AUT on. 
This work is being done in the context of Calabash 2.0 support and CBXDriver support.

Device is responsible for inferring which device to target

---

lib/run_loop/detect_aut/detect.rb
spec/lib/detect_aut/detect_spec.rb

This is a high-level API to infer what app is under test.
At the moment Calabash + RunLoop share responsibility for determining what app is under test.
The user can indicate the AUT using:
* APP, APP_BUNDLE_PATH, and BUNDLE_ID environment variables
* APP_BUNDLE_PATH constant
* `:app`, `:bundle_id`, and `:app_bundle_path` launch options
Further, Calabash users expect their .app bundles to be autodetected.
At the moment, the code to sort out all this options is more than a bit confusing and is _duplicated in run-loop and calabash-ios_.
XCUITest/CBXDriver and Calabash 2.0 will add more options/ENV vars.
This PR is part of an on-going effort to simplify the interaction between RunLoop and calabash-cucumber/launcher.rb.

DetectAUT.detect_app_under_test

---

lib/run_loop/core.rb
spec/lib/core_spec.rb
spec/resources.rb

RunLoop should be responsible for determining the `:uia_strategy` given the launch options and the environment.
At the moment both Calabash 2.0 and Calabash 0.x implement this logic.  Further, in both cases, the logic requires calls to RunLoop to determine what the target device is and the Xcode version.
This change is made in the context of reducing the complexity in calabash-cucumber/launcher.rb to make space for launching with XCUITest/CBXDriver.

Core.detect_uia_strategy given options and RunLoop::Device

---

lib/run_loop/core.rb
lib/run_loop/detect_aut/detect.rb
lib/run_loop/environment.rb
lib/run_loop/instruments.rb
spec/lib/core_spec.rb
spec/lib/detect_aut/detect_spec.rb
spec/lib/environment_spec.rb
spec/lib/instruments_spec.rb

RunLoop is now responsible for inferring the App Under Test and Device Under Test by inspecting the options passed to `Core.run_with_options` _and_ the ENV.
This relieves the clients (Calabash iOS and Calabash 2.0) from having to do any inference at all to try to deduce what the user wants to do.
Clients can now simply pass a Hash of launch options to `RunLoop.run` - there is no need for Calabash to try to rationalize the launch arguments and ENV.
This work is in the context of preparing for XCUITest/CBXDriver support.

Core.run_with_options improve the way AUT and DUT are inferred

---

lib/run_loop/core_simulator.rb
spec/lib/core_simulator_spec.rb

Progress on **Catch iOS Simulator errors when launching and retry** #242
At the moment, we sleep between retries, but a failed launch could me that the entire simulator state is bad which would require a `CoreSimulator.terminate_core_simulator_processes`.

CoreSim#launch - retry on errors

---

lib/run_loop/instruments.rb
spec/integration/instruments_spec.rb
spec/lib/instruments_spec.rb

#kill_instruments branched on Xcode >= 6 to determine which kill signal to seen to `instruments`.   Since we are always executing in Xcode >= 6 environments, we can drop this branching.

Instruments#kill_instruments no longer branches on Xcode version

---

lib/run_loop/cli/simctl.rb

See https://github.com/calabash/run_loop/pull/420
Doctor ensures there are no 'hidden' apps

CLI: simctl doctor erases sims first

---

lib/run_loop/app.rb
lib/run_loop/ipa.rb
spec/lib/app_spec.rb
spec/lib/ipa_spec.rb

This information can be used to determine the provenance of a .app and .ipa to ensure that you are testing the correct binary. 
* #marketing_version <= CFBundleShortVersionString
* #build_version <= CFBundleVersionString

App and Ipa can return version info

---

lib/run_loop/core_simulator.rb
lib/run_loop/simctl.rb
spec/lib/core_simulator_spec.rb

Fixes **RESET_BETWEEN_SCENARIOS has stopped working** #426
`simctl get_app_container` requires the device to be booted on El Cap.  On Yosemite, it works without the device being booted.  Testing shows that moving the device in and out of the booted state is problematic.
To address incomplete app installations (the reason for changing over to simctl), #installed_app_bundle_dir  verifies the correctness of an app installation and cleans up if it encounters an incomplete install.

CoreSim#installed_app_bundle_dir stop using 'simctl'

---

lib/run_loop/core.rb
lib/run_loop/template.rb
scripts/lib/log.js
scripts/run_loop_basic.js
scripts/run_loop_fast_uia.js
scripts/run_loop_host.js
scripts/run_loop_shared_element.js
spec/lib/core_spec.rb
spec/lib/template_spec.rb

While analysing an issue UITest, I stumbled upon a change in behavior introduced by **Extract Logger and onAlert to a single JavaScript file using erb templates** #261.
In a nutshell, RunLoop was no longer flushing the UIALogger buffer.
I took this chance to rename the `:no_flush` option to `:flush_uia_logs`.  The old `:no_flush` option is respected and there is special XTC support. 
ATTN: @svevang We missed a spot. :8:

Restore UIALogger flushing and ensure variables are substituted properly.

---

CHANGELOG.md
lib/run_loop/core_simulator.rb
lib/run_loop/version.rb

* Restore UIALogger flushing and ensure variables are substituted
properly. #430
* DotDir: symlink to current result #429
* Relax deprecation warnings @TeresaP, @jane-openreply, and others
* RESET\_BETWEEN\_SCENARIOS has stopped working #426 @ankurgamit

Gem: bump version to 2.1.1.pre2

---

lib/run_loop/sim_control.rb
lib/run_loop/simctl.rb
spec/lib/simctl_spec.rb
spec/resources/simctl_json_devices.rb

Starting Xcode 7.3, simctl can output stderr logs.  `command_runner_ng` combines stderr and stdout (for better or worse).
Fixes **udid variable in device.rb is nil on first launch** [#1058](https://github.com/calabash/calabash-ios/issues/1058)

Filter new Xcode 7.3 simctl stderr output from `simctl list devices`

---

lib/run_loop/core_simulator.rb
spec/integration/core_simulator_spec.rb
spec/lib/core_simulator_spec.rb

After an app launch times out:
1. terminate the CoreSimulator processes,
2. launch the app,
3 and then sleep.
Progress on:
* **Catch iOS Simulator errors when launching and retry** #242
* **`simctl install` on iPad Simulators installs an app that is not recognized by Springboard or simctl* #435 - possible Apple bug.
There is now an integration test that checks the retry logic and heuristics.

Improve retry strategy for app launch on simulators

---

CHANGELOG.md
lib/run_loop/version.rb

* Improve retry strategy for app launch on simulators #436
* Fix instruments CLI rspec tests. #416
* CoreSim#launch: improve retrying #434
* Filter new Xcode 7.3 simctl stderr output from `simctl list devices`
#433
* Simctl is responsible for collecting devices on Xcode > 6
* CoreSim: patch retry on failed app launch 5300542
* Restore UIALogger flushing and ensure variables are substituted
properly. #430
* DotDir: symlink to current result #429
* Relax deprecation warnings @TeresaP, @jane-openreply, and others
* RESET\_BETWEEN\_SCENARIOS has stopped working #426 @ankurgamit

Gem: bump version to 2.1.1.pre3

---

lib/run_loop/xcuitest.rb
spec/lib/xcuitest_spec.rb

XCUITest: rename the xcodebuild log file

---

CHANGELOG.md
lib/run_loop/version.rb

* Replace SimControl with Simctl #441
* Fixing syntax error in host script #438 @garyjohnson
* Improve retry strategy for app launch on simulators #436
* Fix instruments CLI rspec tests. #416
* CoreSim#launch: improve retrying #434
* Filter new Xcode 7.3 simctl stderr output from `simctl list devices`
#433
* Simctl is responsible for collecting devices on Xcode > 6
* CoreSim: patch retry on failed app launch 5300542
* Restore UIALogger flushing and ensure variables are substituted
properly. #430
* DotDir: symlink to current result #429
* Relax deprecation warnings @TeresaP, @jane-openreply, and others
* RESET\_BETWEEN\_SCENARIOS has stopped working #426 @ankurgamit

Gem: bump version to 2.1.1.pre5

---

lib/run_loop/environment.rb
lib/run_loop/logging.rb
spec/lib/logging_spec.rb

Calabash wants to use these.
**Added draft tree feature for console** [#1070](https://github.com/calabash/calabash-ios/pull/1070)
ATTN: @ark-konopacki

Expose color methods as public API

---

lib/run_loop.rb
lib/run_loop/encoding.rb
lib/run_loop/xcrun.rb
spec/lib/encoding_spec.rb
spec/lib/xcrun_spec.rb

We need the coercion method in other places.
This is a strict rename + extract refactor.

Encoding: extract uft8 coercion method from Xcrun

---

lib/run_loop.rb
lib/run_loop/shell.rb
spec/lib/shell_spec.rb

I want a mixin to provide safe execution of shell commands.
Progress on:
* Pass all `read` calls through utf-8 filter #230
* run all shell commands through Xcrun #285

Shell: a mixin for executing shell commands safely

---

lib/run_loop/device.rb
spec/integration/core_simulator_spec.rb
spec/lib/device_spec.rb

Progress on:
* **`simctl install` on iPad Simulators installs an app that is not recognized by Springboard or simctl** #435
* **Testing on iOS Simulators is slow in Xcode 7** [#41](https://github.com/xamarinhq/test-cloud-frameworks/issues/41)
I rewrote the "simulator stable" algorithm.  It is now much easier to explain and has consistent behavior.  The notion of "quiet time" in the previous version was not really working.
The bad news is that I am still seeing failures on iOS 9 iPads.  The good new is that they happen less frequently.

SpringBoard cannot detect app installed by simctl on iPad

---

lib/run_loop/core.rb
lib/run_loop/detect_aut/detect.rb
spec/lib/detect_aut/detect_spec.rb

Resolves **`nil` path when preparing simulator in compatible arches check when APP was not set correctly** #463
@acroos

Catch invalid APP and device target settings

---

lib/run_loop/xcuitest.rb

* Interface to /device route
* tap_coordinate takes options
* try to manage testmanagerd
* check response body for error
This is a bit of a WIP, but needs to be merged to test the interface to `xctestctl` and continue orientation testing.

XCUITest interface part 2

---

lib/run_loop.rb
lib/run_loop/abstract.rb
lib/run_loop/physical_device/life_cycle.rb
spec/lib/abstract_spec.rb
spec/lib/physical_device/life_cycle_spec.rb

We want an API for handling an app's life cycle on physical devices.

Physical device app LifeCycle API

---

lib/run_loop/xcuitest.rb

It is not clear yet whether or not touch, double_tap, and two_finger_tap
will be part of the XCUITest API, but they are really useful for debugging.
Removes the make_coordinate_gesture_request interface in favor of
`#perform_coordinate_gesture`

XCUITest: simplify the comman gestures API

---

.irbrc
bin/dnssd
lib/run_loop.rb
lib/run_loop/dnssd.rb
run_loop.gemspec

Demonstrates how to discover Bonjour services for the purpose of finding the IP and port of bonjour service on a physical device.
This will only work on some networks and it is not clear yet how helpful this will be.

DNSSD: detect bonjour services

---

lib/run_loop/encoding.rb
lib/run_loop/environment.rb
lib/run_loop/xcuitest.rb
run_loop.gemspec
spec/lib/encoding_spec.rb
spec/lib/environment_spec.rb
spec/lib/xcuitest_spec.rb

Progress on:
* XTC support for DeviceAgent
Resolves (for run_loop):
* [JIRA: calabash-ios/UITest/XDB should respect a DEVICE_AGENT_URL env var](https://xamarin.atlassian.net/browse/TCFW-84)
The order of preference is:
1. DEVICE_AGENT_URL
2. If simulator target, use the default 127.0.0.1 hostname and port
3. If DEVICE_ENDPOINT, use the hostname provided and change the port
4. Try to deduce the hostname using the device name e.g. Joshuas-iPad.local

XCUITest respects to DEVICE_AGENT_URL

---

lib/run_loop/codesign.rb
lib/run_loop/core_simulator.rb
lib/run_loop/device.rb
lib/run_loop/dylib_injector.rb
lib/run_loop/instruments.rb
lib/run_loop/otool.rb
lib/run_loop/shell.rb
lib/run_loop/sim_control.rb
lib/run_loop/simctl.rb
lib/run_loop/strings.rb
lib/run_loop/xcrun.rb
lib/run_loop/xcuitest.rb
spec/integration/core_simulator_spec.rb
spec/integration/xcrun_spec.rb
spec/lib/app_spec.rb
spec/lib/codesign_spec.rb
spec/lib/core_simulator_spec.rb
spec/lib/device_agent/framework_spec.rb
spec/lib/device_spec.rb
spec/lib/dylib_injector_spec.rb
spec/lib/instruments_spec.rb
spec/lib/otool_spec.rb
spec/lib/physical_device/life_cycle_spec.rb
spec/lib/shell_spec.rb
spec/lib/sim_control_spec.rb
spec/lib/simctl_spec.rb
spec/lib/strings_spec.rb
spec/lib/xcrun_spec.rb

I have been using `#exec` and `.exec` methods on various classes as shorthand for "shell out an run this command".  _exec_ is not a good name because it conflicts with `Kernel#exec`.
This is renaming refactor.  `Xcrun#exec` is preserved for backward compatibility.
This work is done in the context of XCUITest/DeviceAgent support.
Related:
* remove Xcode#exec #478

Rename exec methods in various classes

---

lib/run_loop/detect_aut/detect.rb
spec/lib/detect_aut/detect_spec.rb

While working on a Xamarin sample project, I found the search depth of "5" to be too small.  Increased to 10.

DetectAUT: increase search depth for AUT for Xamarin projects

---

.travis.yml

* Dropping Xcode 6 testing; no longer supporting Xcode 6
* Force macOS 10.11 and Xcode 7.3
* Use precompiled rubies to address rvm SSL install errors on Travis

Travis uses macOS 10.11 and Xcode 7.3

---

lib/run_loop/core_simulator.rb
lib/run_loop/process_terminator.rb
lib/run_loop/sim_control.rb
spec/lib/core_simulator_spec.rb

Completes **replaces calls to `xcrun ps` with `ps`**[JIRA](https://xamarin.atlassian.net/browse/TCFW-205).
In Xcode 8, `ps` is not available in the context of `xcrun` - this is causing the unit test runner in DeviceAgent.iOS to fail.
After reviewing the code, I created this issue **Create a class or module for interacting with `ps`** #487 which is part of this epic **Pass all `read` calls through utf-8 filter** #230.

Don't call ps in the context of xcrun

---

lib/run_loop.rb
spec/integration/core_simulator_spec.rb
spec/lib/run_loop_spec.rb

RunLoop needs to know when to use UIAutomation/instruments and XCUITest/DeviceAgent.
`RunLoop.run` now responds to the `:gesture_performer`.  Users should never set this option, it is for gem maintainers only.  Users should rely on the default behavior.
The default behavior is:
* :instruments <== Xcode <= 7
* :device_agent <== Xcode >= 8
At the moment, RunLoop will raise an error if the Xcode version is incompatible with the iOS version: Xcode >= 8 and iOS < 9.0.
Please be aware that there is no released version of Calabash that can use :device_agent.
Alpha level support for DeviceAgent will be available in Calabash > 0.19.2 (next release).

RunLoop.run detects and respects gesture performer key

---

lib/run_loop/device_agent/ios_device_manager.rb

iOSDeviceManager requires the simulator be in state "Shutdown" before is can launch the CBX-Runner.
There are a couple of options:
1. CoreSimulator.quit_simulator detects a Booted sim and waits for it to have state "Shutdown".  This is expensive because it requires `Simctl` to either update the state of every known simulator or to ask for all the simulators (and thereby getting the state).  Either of these approaches might take > 10 seconds.
2. Call out to iOSDeviceManager#kill_simulator - this waits for "Shutdown".
3. After the CoreSimulator.quit_simulator call and before the iOSDeviceManager `start_test`, insert a `CoreSimulator.wait_for_simulator_state(device, "Shutdown")`.
I opted for 3 because it was the fastest to implement. Option 2 is attractive and is arguably the best solution, …

iOSDeviceManager: wait for sim 'shutdown' state before launching

---

.irbrc
bin/dnssd
run_loop.gemspec

Calabash 2.0 depends on run-loop and must be able to install on Windows and Linux environments.  The dnssd gem is macOS only.

Gem: require dnssd only on macOS

---

spec/lib/process_waiter_spec.rb

On macOS 10.11.6, ps is not returning any results for a 'ruby' process.

Spec: try searching for Finder in ProcessWaiter examples

---

bin/dnssd
lib/run_loop.rb
lib/run_loop/dnssd.rb
run_loop.gemspec

The dnssd gem is macOS only.
Calabash 2.0 and x-platform projects depend on run-loop and must be able to install on Windows and Linux environments. 
A native extension is not practical (it works locally), because it would require the run_loop gem be whitelisted on the Xamarin Test Cloud.
I am going to make this change as patch release because the dnssd interface is a command line development tool and not something that is used during UI testing.
[JIRA](https://xamarin.atlassian.net/browse/TCFW-256)
I ran the test-cloud-command-line test against this branch.

Remove dnssd dependency

---

lib/run_loop.rb
lib/run_loop/device_agent/ios_device_manager.rb
lib/run_loop/environment.rb
lib/run_loop/physical_device/ios_device_manager.rb
spec/lib/environment_spec.rb

We want an interface to iOSDeviceManager's physical device management tools.
This is a first pass and should be considered a work in progress.
There are no unit tests for the interface.

Start PhysicalDevice::LifeCycle::IOSDeviceManager implementation

---

lib/run_loop/regex.rb
spec/lib/regex_spec.rb

Regex reports iOS 10 as "0.0"  Whoops!
[JIRA](https://xamarin.atlassian.net/browse/TCFW-285)

Regex: expand VERSION_REGEX to support iOS 10.0

---

lib/run_loop/shell.rb
spec/lib/shell_spec.rb

Shell.run_unix_command was raising a TimeoutError if the command failed to execute (:exit_status => nil).  It now correctly raises a RunLoop::Shell::Error.
[JIRA](https://xamarin.atlassian.net/browse/TCFW-272)

Shell: raise the correct error when command fails

---

lib/run_loop/physical_device/ios_device_manager.rb
spec/lib/physical_device/ios_device_manager_spec.rb

The DeviceAgent Frameworks.zip must be expanded before iOSDeviceManager can be invoked.
[JIRA](https://xamarin.atlassian.net/browse/TCFW-286)

LifeCycle: IOSDeviceManager expands the Frameworks.zip if necessary

---

lib/run_loop/device.rb
spec/lib/device_spec.rb

`Device#simulator_set_language` was failing silently if PlistBuddy was not in the PATH.

Device: assume PlistBuddy is not in PATH when setting the simulator language

---

.irbrc
lib/run_loop/cli/cli.rb
lib/run_loop/core_simulator.rb
lib/run_loop/device.rb
lib/run_loop/shell.rb
lib/run_loop/sim_control.rb
lib/run_loop/simctl.rb
spec/integration/core_simulator_spec.rb
spec/integration/core_spec.rb
spec/integration/simctl_spec.rb
spec/lib/core_simulator_spec.rb
spec/lib/device_spec.rb
spec/lib/shell_spec.rb
spec/lib/sim_control_spec.rb
spec/lib/simctl_spec.rb
spec/resources.rb

Resolves:
* calls to simctl need to guard against wrong CoreSimulator service loaded [JIRA](https://xamarin.atlassian.net/browse/TCFW-301)
Progress on:
* Complete simctl interface #293
This also brings us one step closer to being able to see if `fbsimctl` can be a replacement for `simctl`.
Joshua, I am particularly interested to see these two integration examples pass on your machine:
```
$ git fetch
$ git co -to origin/feature/add-guard-for-incompatible-CoreSimulator-service
$ bundle update
$ be rspec spec/integration/simctl_spec.rb
$ be rspec spec/integration/core_simulator_spec.rb
```

All simctl commands are performed through Simctl instance

---

lib/run_loop/app.rb
lib/run_loop/otool.rb
spec/integration/otool_spec.rb
spec/lib/app_spec.rb
spec/lib/otool_spec.rb

> Currently the new LLVM-based otool(1) exits with a non-zero status on the first error it encounters for the files on the command line, including treating non-object files as errors. This differs from the previous otool(1), available now as otool-classic(1), which will process all files on the command line even if some have errors. otool-classic(1) will treat non-object files as a warning instead of an error. (26828015)
The Otool API changed:
```
RunLoop::Otool.new("path/to/file").executable?
xcode = RunLoop::Xcode.new
RunLoop::Otool.new(xcode).executable?("path/to/file")
```
Completes:
* run-loop needs to update its `otool` implementation to respond to Apple changes [JIRA](https://xamarin.atlassian.net/projects/TCFW/issues/TCFW-365)
```
$ be rspec spec/integration/otool_spec.rb
```

Respond to Xcode 8 otool changes

---

.irbrc
lib/run_loop.rb
lib/run_loop/core.rb
lib/run_loop/device_agent/client.rb
spec/lib/run_loop_spec.rb

RunLoop.run now responds to `:automator` instead of `:gesture_performer`.

DeviceAgent: replace :gesture_performer with :automator

---

lib/run_loop/device_agent/client.rb

Stabilize iOS 10 tests on the Xamarin Test Cloud

DA:Client: increase default timeouts for Xamarin Test Cloud

---

lib/run_loop/core_simulator.rb
spec/lib/core_simulator_spec.rb

There are now two apps to install: DeviceAgent and the AUT.  The simulator-stable method has not been optimized for Xcode 8 simulators.  I have been testing with this patch for two weeks and I have not encountered any problems.

CoreSim: don't wait after simctl install

---

lib/run_loop/device_agent/client.rb

DeviceAgent can interact with SpringBoard alerts (AKA Privacy Alerts).
This is a prototype API - it is documented as private.  It can change at any time.
Here are some possible APIs.
```
:app => An alert generated by the Application Under Test
:spring_board => An alert generated SpringBoard (e.g. Privacy Alert)
:any => Either :app or :spring_board
def alert(type=:app)
def alert?(type=:app)
def wait_for_alert(type=:app, timeout, &block)
def wait_for_no_alert(type=:app, timeout, &block)
```
This is also a possibility:
```
def alert
def alert.visible?
```
Feedback is welcome.
@TobiasRoikjer Comments in the context of Calabash 2.0?

DA:Client: prototype API for SpringBoard alerts

---

lib/run_loop/device_agent/client.rb
lib/run_loop/device_agent/ios_device_manager.rb
spec/integration/device_agent/client_spec.rb
spec/lib/device_agent/client_spec.rb

Users are reporting timeouts when trying to install DeviceAgent to their physical devices.  This is one-time performance hit for each new release of DeviceAgent.  We are working hard to make this faster.  Expect improvements soon.
This PR increases the default timeout to 60 seconds (up from 30).
You can override this value if it does not work in your environment.
```
options = {
:device_agent_install_timeout => 240
}
launcher.relaunch(options)
```     
Cucumber users can also override in your `features/support/env.rb.`
```
RunLoop::DeviceAgent::Client::DEFAULTS[:http_timeout] = 60
```

Allow the user to increase the default DeviceAgent install time

---

lib/run_loop/core.rb
lib/run_loop/device_agent/client.rb
lib/run_loop/dylib_injector.rb
spec/lib/core_spec.rb
spec/lib/device_agent/client_spec.rb
spec/lib/http/retriable_client_spec.rb

This feature is necessary to provide backward compatibility. 
ATTN @MortenGregersen

Support LPServer dylib injection on Simulators when running with DeviceAgent

---

lib/run_loop/device_agent/client.rb

Move the instantiation of the client and request inside begin/rescue block
as discussed with @jmoody on gitter.im

Fix retry with dylib injection and DeviceAgent

---

run_loop.gemspec

* Update HTTP Client to 2.7.1 or better [JIRA](https://jira.xamarin.com/browse/TCFW-85)

Gem: force HTTPClient 2.7.1 or higher

---

lib/run_loop/core.rb
spec/lib/core_spec.rb

Xcode 8 GM ships with iPhone 7 iOS 10 simulator.

Core: default sim for Xcode 8 is iPhone 7 iOS 10

---

lib/run_loop/core_simulator.rb
lib/run_loop/device.rb
spec/lib/core_simulator_spec.rb

Rolls back this 26edcc68f781745f7cbb7c2dc9b420f6ca55685f change and adds documentation about why it is necessary.
Fixes:
* Could not install app on simulator on CI [#1163](https://github.com/calabash/calabash-ios/issues/1163)
* Flickering example in Jenkins CI
ATTN: @JoeSSS

CoreSim: waiting is necessary after simctl install

---

lib/run_loop/device_agent/client.rb

Improve text entry by providing a way to enter text without texting for the keyboard.
The Calabash client already checks for the keyboard.  Calling the existing `#enter_text` in method adds a duplicate keyboard visible check which is expensive (time).
We've identified some problems in the DeviceAgent stack.  This a first step toward fixing problems with text entry.
Progress on:
* keyboard_enter_text times out typing long text [#1158](https://github.com/calabash/calabash-ios/issues/1158)
* Can't type in one of the field of our APP [#1155](https://github.com/calabash/calabash-ios/issues/1155)
* In my app's safari webview, keyboard_visible? command returns "false" while the device_agent.keyboard_visible? command returns "true" [#1166](https://github.com/calabash/calabash-ios/issues/1166)

DeviceAgent::Client: enter text without keyboard check

---

lib/run_loop/device_agent/client.rb
spec/lib/device_agent/client_spec.rb

Completes:
* DeviceAgent::Client#tree needs a longer timeout [JIRA](https://jira.xamarin.com/browse/TCFW-672)
Adds support for "get all" queries.
```
query({})
query({all: true})
```

DeviceAgent::Client:  add support for query("*") and query("all *")

---

lib/run_loop/device_agent/client.rb

We've discovered some problems in DeviceAgent's ability to enter text.
While we sort this problem out, we'll increase the enter text timeouts.
Progress on:
* keyboard_enter_text times out typing long text [#1158](https://github.com/calabash/calabash-ios/issues/1158)
* Can't type in one of the field of our APP [#1155](https://github.com/calabash/calabash-ios/issues/1155)

DA:Client: increase timeouts for enter text calls

---

lib/run_loop/patches/awesome_print.rb

Progress on:
* device_agent error - undefined method 'ai' [#1208](https://github.com/calabash/calabash-ios/issues/1208)

Gem: patch awesome_print for BasicObject

---

lib/run_loop/device_agent/client.rb

**Motivation**
Numeric keyboards pass in a number where we expected a string input - so adding `to_s` to make the request with a string.
Addresses calabash/calabash-ios#1176

Turns enter text input parameter to string for numeric keyboards

---

scripts/lib/on_alert.js

Added translations for the Permissions Alerts messages, because Calabash was not able to automatically dismiss Portuguese alerts.
I used Permissions.app to get this messages. I could not run Permissions.app in a Device, so all messages came from an iPhone 6 simulator, running iOS 9.3. Ruby 2.3.1p112 and calabash-ios 0.20.3.
Then I used Permissions.app to check if this solved the problem and the scenarios passed.
For newer versions of iOS SDK, I opened the Issue [#1226](https://github.com/calabash/calabash-ios/issues/1226) in the calabash-ios repository, so DeviceAgent can also be updated.
This is my first pull request for run_loop. Please forgive me if something is not OK. Anything that should change, please let me know and I will fix it in no time.

Added pt-BR translations for permissions alerts

---

lib/run_loop/app.rb
spec/lib/app_spec.rb

Fixes:
* Issues with TTF files - The file was not recognized as a valid object file [#1227](https://github.com/calabash/calabash-ios/issues/1227)
Thanks @raffabhaktin for reporting.

App: fix TrueType font extension to avoid otool failures

---

Rakefile
lib/run_loop/cli/simctl.rb

* Removes the need to boot a simulator before tailing.
* Tracks all simulators for the active Xcode - no need restart tailing if the simulator under test changes.

run-loop simctl tail shows all simulator logs

---

scripts/ci/jenkins/run.sh
spec/integration/core_simulator_spec.rb
spec/integration/simctl_spec.rb

Jobs are being migrated from Xcode 7 to Xcode 8 on Jenkins.  As a result it is possible for an Xcode 8 job to leave the CoreSimulatorService in a bad state which will cause subsequent Xcode 7 jobs to fail.

Jenkins: ensure the correct CoreSimulatorService is loaded

---

lib/run_loop/device_agent/client.rb

Users are complaining that DeviceAgent installs are timing out.
I added a documentation example of how to increase the install timeout:
```
RunLoop::DeviceAgent::Client::DEFAULTS[:device_agent_install_timeout] = 120
```
and bumped the default timeout to 90 seconds.
We've noticed that DeviceAgent queries can take a very long time execute.
I bumped the default HTTP timeout to 20 seconds.

Increase DeviceAgent timeouts

---

lib/run_loop/device_agent/client.rb
lib/run_loop/device_agent/ios_device_manager.rb

iOSDeviceManager can find a CODE_SIGN_IDENTITY so there is no need to set this variable.
Setting CODE_SIGN_IDENTITY is still supported - if set, iOSDeviceManager will attempt to sign with the provided identity.

CODE_SIGN_IDENTITY is not longer required

---

lib/run_loop/device_agent/client.rb

Completes:
* No longer possible to pass Environment variables to instance [#1172](https://github.com/calabash/calabash-ios/issues/1172)
The `:args` key uses the same conventions as with UIAutomation:
```
options = {
:args =>  ["-AppleLanguages", "(da)",
"-AppleLocale", "da"]
}
```
To see this in action, try:
```
options = {
:args => ["-NSShowNonLocalizedStrings", "YES"]
}
```
UIAutomation allowed environment variables to be set.  Calabash did not have an official API for this, but users were able to override the `:args` option using the `-e` flag.
This PR does not provide backward-compatible support for the `-e` flag.  Instead, it provides a separate option: `:env`.  To be backward compatible, follow the example below.
```
if uia_available?
options = {
:args =>  [  "-e", "USER_NAME", …
```

DA:Client: launch AUT with args and environment

---

lib/run_loop/device_agent/client.rb
spec/integration/simctl_spec.rb

There are at least 2 flickering examples:
* rspec ./spec/integration/device_agent/client_spec.rb:44 # RunLoop::DeviceAgent::Client#launch ios_device_manager
* rspec ./spec/integration/simctl_spec.rb:17 # RunLoop::Simctl #wait_for_shutdown

Stabilize Simulator examples on Jenkins

---

lib/run_loop/device_agent/client.rb
spec/integration/simulator_compatibility_spec.rb

This check has been missing from `DeviceAgent::Client.run`
Progress on:
* Integration examples need attention #243

DeviceAgent::Client: check simulator/application architecture compatibility

---

lib/run_loop/core_simulator.rb
lib/run_loop/process_waiter.rb
spec/integration/process_waiter_spec.rb

Progress on:
* Create a class or module for interacting with `ps` #487
* Pass all read calls through utf-8 filter #230

ProcessWaiter: improve process detection

---

lib/run_loop/core_simulator.rb
lib/run_loop/device.rb
spec/lib/core_simulator_spec.rb

The simulator wait for stable state no longer waits for the the SHA and the simulator log to stabilize.  Instead, it waits for `launchd_sim` to start critical simulator processes.  This means that CoreSimulator `install` and `uninstall` should not call `Device#simulator_wait_for_stable_state` because, by definition, the simulator must be stable before install/uninstall are called.
* A first launch check to `Device#simulator_wait_for_stable_state`.
* CoreSimulator install and uninstall wait for the _size_ of the simulator directory to match an expectation before proceeding.

Decouple simulator wait for stable state and CoreSim install and uninstall

---

lib/run_loop/core_simulator.rb
lib/run_loop/device.rb
lib/run_loop/device_agent/client.rb
lib/run_loop/process_waiter.rb
spec/integration/core_simulator_spec.rb
spec/integration/device_spec.rb
spec/lib/core_simulator_spec.rb

Now that simulators are not always relaunched, we need to detect states where the simulator _must_ be relaunched to ensure stability.
* If the DeviceAgent is running, but was launched by Xcode - relaunch.
* If the AUT is running, but not launched by run-loop - relaunch.  The assumption is that the AUT is attached to Xcode somehow.

CoreSimulator relaunches the simulator if app state is not acceptable

---

lib/run_loop/core.rb
lib/run_loop/core_simulator.rb
lib/run_loop/device_agent/client.rb
lib/run_loop/device_agent/ios_device_manager.rb
spec/integration/core_simulator_spec.rb
spec/integration/device_spec.rb
spec/integration/dylib_injector_spec.rb
spec/integration/run_sim_spec.rb
spec/integration/simctl_spec.rb

Starting in run-loop 2.3.0, the Simulator will not be relaunch automatically before the start of each test.  Many users have requested this feature.  For some users, however, this will introduce instability to their test runs. 
To provide backward compatibility, we've decided that  UIAutomation runs will continue to relaunch the simulator whenever `Calabash::Cucumber::Launcher#relaunch` is called.  DeviceAgent runs will try to keep the simulator running whenever possible.  Users can override this behavior and force the simulator to be relaunched by calling `Calabash::Cucumber::Launcher#relaunch` with the `:relaunch_simulator => true` option.
If users want similar behavior for UIAutomation runs, we can discuss adding it in run-loop 2.3.1.

Allow user to force simulator relaunch when running with DeviceAgent

---

lib/run_loop/device.rb
spec/lib/device_spec.rb

While testing, I discovered two phenomena:
1.  iOS <= 8 Simulators were always waiting the full 30 seconds for the simulator to become stable and
2. iOS >= 10.1 Simulators take longer than 30 seconds to fully boot after an erase.
The first problem was fixed by filtering the list of required processes by iOS version.
The default sim stable timeouts have been changed to 240 seconds for CI and 120 seconds locally.   Testing shows that on a reasonably fast machine with encryption enabled, it takes ~70 seconds to boot an iOS 10.1 simulator.  🎱

Improve Device#simulator_wait_for_stable_state for iOS <= 8 and iOS >= 10.1

---

lib/run_loop/core_simulator.rb

I have noticed that after hours of testing against the simulators, they become unstable.
Reviewing the running process, I found hundreds of `UserEventAgent`, `MobileSMSSpotlightImporter`, and `mobileassetd` processes.
Killing these processes makes the simulator stable again.
In addition, I found many more orphaned Simulator processes.  `RunLoop::CoreSimulator.terminate_core_simulator_processes` is now more aggressive about terminating process.
```
$ be run-loop simctl manage-processes
```

CoreSimulator manages more processes for Xcode 8 and Sierra

---

.travis.yml

In recent test runs, one test is failing on Travis.  The failure is not reproducible on Jenkins or locally on macOS Sierra or El Cap.
We should be running against fewer rubies.

Stabilize Travis runs

---

lib/run_loop/directory.rb

Occasionally `File.size` or the `Directory.skip_file?` check raises `Errno::ENOENT` errors.  We can safely ignore this error and other errors.
Replaces #597

Directory: rescue errors during skip check and File.size

---

lib/run_loop/core.rb
lib/run_loop/xcode.rb
spec/lib/core_spec.rb
spec/lib/xcode_spec.rb

Xcode 8.3 beta 3 is out.
The DeviceAgent stack is not ready for Xcode 8.3.

Prepare for Xcode 8.3 support

---

lib/run_loop/device_agent/client.rb

This check quits the simulator and defeats the purpose of **CoreSim: quit simulator only when necessary** #580
Thanks @JoeSSS for reporting and diagnosing.

DeviceAgent::Client: skip ensure software keyboard check

---

lib/run_loop/core_simulator.rb

Resolves:
* [iOS Simulator] RuntimeError: Expected 'Shutdown but found 'Booted' after waiting #599
* Error - Expected 'Shutdown but found 'Booted' after waiting [#1270](https://github.com/calabash/calabash-ios/issues/1270)
Supersedes:
* Resolve issue #599 - Fix broken launch of iOS Simulator with RESET_BETWEEN_SCENARIOS enabled #600

CoreSim: quit simulator if before resetting app sandbox

---

lib/run_loop/xcode.rb
spec/integration/xcode_spec.rb
spec/lib/run_loop_spec.rb
spec/lib/xcode_spec.rb

Xcode#to_s is raising errors on Test Cloud.
Progress on:
* https://github.com/xamarin/test-cloud-frontend/issues/2628

Xcode#version returns 0.0.0 on XTC on RuntimeErrors

---

scripts/lib/on_alert.js

Resolves:
* calabash should automatically accept new VPN configurations [#1279](https://github.com/calabash/calabash-ios/issues/1279)

JS: add VPN definition to on_alert

---

lib/run_loop/device_agent/client.rb

Completes:
* Allow users to interact with SpringBoard alerts [TCFW 907](https://jira.xamarin.com/browse/TCFW-907)
* Possibility to ignore system level alert views #66
Progress on:
* Allow Users to Accept "Open In" Alerts [TCFW 1081](https://jira.xamarin.com/browse/TCFW-907)
```
set_dismiss_springboard_alerts_automatically(true_or_false)
springboard_alert_visible?
springboard_alert
wait_for_springboard_alert
wait_for_no_springboard_alert
dismiss_springboard_alert(button_title)
```
Tested against changes in DeviceAgent:
*  Allow users to interact with SpringBoard alerts and control automatic dismissal  [#205](https://github.com/calabash/DeviceAgent.iOS/pull/205)
```
$ be cucumber -t @springboard_alerts
@meta
Feature: Meta Routes
@springboard @springboard_alerts
Scenario: SpringBoard alerts …
```

API for managing SpringBoard alerts manually

---

lib/run_loop/device_agent/ios_device_manager.rb
lib/run_loop/device_agent/launcher_strategy.rb
lib/run_loop/device_agent/xcodebuild.rb
spec/lib/device_agent/ios_device_manager_spec.rb
spec/lib/device_agent/launcher_strategy_spec.rb
spec/lib/device_agent/xcodebuild_spec.rb

Users are reporting that on the first run, the ~/.run-loop/DeviceAgent directory does not exist.
Progress on:
* run-loop 2.4.1 [3102](https://msmobilecenter.visualstudio.com/Test/_workitems/edit/3102)
The log file for iOSDeviceManager + xcodebuild test-without-building is:
* ~/.run-loop/DeviceAgent/current.log
ATTN @JoeSSS

Migrate ~/.run-loop/xcuittest to ~/.run-loop/DeviceAgent to ensure xctestrun run exists

---

lib/run_loop/core.rb
lib/run_loop/xcode.rb
spec/lib/core_spec.rb
spec/lib/xcode_spec.rb

This change set does not provide testing support for Xcode 9/iOS 11 - for example DeviceAgent is not launching on iOS Simulators.

Initial Xcode 9/iOS 11 support

---

lib/run_loop/device_agent/ios_device_manager.rb
spec/lib/device_agent/ios_device_manager_spec.rb

Progress on:
* xcodebuild test-without-building causes iOS Simulator to relaunch _after_ user asks for simulator to be relaunched #618
In run-loop 2.4.0, we replaced `iOSDeviceManager start_test`  with `xcodebuild test-without-building` to launch DeviceAgent.  When a simulator is the target (id=<destination>) of `xcodebuild test-without-building` and the simulator is terminated, xcodebuild will relaunch the simulator and the DeviceAgent (#618). 
This change set will also clean up existing `xcodebuild  test-without-building` processes that are stale.

Xcodebuild: manage existing test-without-building processes

---

lib/run_loop/device.rb
spec/lib/device_spec.rb

Occasionally, a simulator's .GlobalPreferences.plist does not exist.

Device: wait for .GlobalPreferences.plist to exist

---

lib/run_loop/core_simulator.rb
spec/lib/core_simulator_spec.rb

DeviceAgent built with Xcode 9 generates an .app bundle with an executable named `DeviceAgent-Runner`.  Previously, the name was `XCTRunner`.

CoreSimulator can handle Xcode 9 DeviceAgent name change

---

lib/run_loop/core_simulator.rb

At some point during Xcode 8, `open -g` stopped launching the Simulator in the background.
When the Simulator is not launched in the background it steals (key application) focus which is disruptive.
This changeset uses AppleScript to force the Simulator into the background after it has been launched.  This is not the perfect behavior:
1. the simulator does steal focus for a moment
2. the simulator becomes hidden - this overrides any "Remain on top" user settings.

CoreSim: simulator does not steal focus when launching

---

run_loop.gemspec

Using bundler 1.15.* and `github =>` or `path =>` in a Gemfile results in:
```
$ bundle update
Invalid gemspec in [lib/run_loop/version.rb]: No such file or directory @ rb_sysopen
```

Gem: fix reference to version.rb for bundler 1.15

---

lib/run_loop/cli/simctl.rb

We recently upgraded our Jenkins machine to Sierra and Xcode 8.3.3 (from El Cap and Xcode 7.3.1).  Since then, our simulator experience has been terrible.  Specifically, `xcodebuild` cannot seem to connect to simulators when running XCTest bundles. 
We know that running:
```
$ run-loop simctl doctor
```
can correct the problem, so we started running that nightly.
However, if there is a lot of activity on Jenkins the XCTest start to fail.
This PR adds two commands that allow us to erase and launch specific simulators.
```
$ run-loop simctl erase # the default simulator
$ run-loop simctl erase <UDID>
$ run-loop simctl erase "iPhone 7 (10.3)" # Instruments simulator name format
$ run-loop simctl launch
```
Progress on:
* Simulators on Jenkins CI machine are failing to launch XCTest …

CLI: add simctl erase and launch commands

---

lib/run_loop/core_simulator.rb
lib/run_loop/device_agent/client.rb
lib/run_loop/device_agent/ios_device_manager.rb
lib/run_loop/device_agent/xcodebuild.rb
spec/integration/device_agent/client_spec.rb
spec/lib/device_agent/ios_device_manager_spec.rb
spec/resources.rb

Completes:
* xcodebuild-kill algorithm does not prevent simulator from relaunching [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/12973)
In run-loop 2.4.0, we replaced `iOSDeviceManager start_test`  with `xcodebuild test-without-building` to launch DeviceAgent.  When a simulator is the target (id=<destination>) of `xcodebuild test-without-building` and the simulator is terminated, xcodebuild will relaunch the simulator and the DeviceAgent.
Related:
* Xcodebuild: manage existing test-without-building processes #625
* Can't change 27753 port for 'iOSDeviceManager' / DeviceAgent-Runner.app #541

Better xcodebuild process management

---

lib/run_loop/device_agent/client.rb

Progress on:
* iOS 11: orientation is being reported incorrectly [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/15051)
DeviceAgent now sleeps after the rotation change and then responds with the new orientation.
In previous versions of iOS, the `XCUIDevice` instance returned the _new_ orientation immediately.  In iOS 11, the new orientation is not available until _after_ the orientation animations have completed.
`POST /rotate_home_button_to` responds to `:seconds_to_sleep_after` parameter to control how long to wait for the orientation update.

Respond to DeviceAgent iOS 11 changes to POST /rotate_home_button_to

---

lib/run_loop/version.rb
spec/lib/version_spec.rb

Completes:
* run-loop #<Version 9.0.0>  >= Version.new("9.0") should be true [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/14915)
I wasted a lot of time last week trying sort out why an iOS Simulator filter-by-version was not working correctly.  Simulators with iOS version 9.0 were not responding to `>=` when tested against version 9.0.0.

Update equality rules for Version class

---

lib/run_loop/l10n.rb
spec/lib/l10n_spec.rb

Completes:
* run-loop: L10n path to UIKit.axbundle needs update for Xcode 9 [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/15391)

L10N: update path to UIKit.axbundle for Xcode 9

---

lib/run_loop/device.rb

The simulator stable algorithm was hanging on Xcode 9 simulators.
Completes:
* run-loop's simulator-stable algorithm should work with Xcode 9.0 [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/10974)

Device: adjust required processes for Xcode 9

---

lib/run_loop/core_simulator.rb

Looking at our CI machine, I found hundreds of orphaned processes related to CoreSimulator.
The expectation is that terminating these processes will improve simulator stability.
"Hope is a straight road to disappointment." 🎱

Update list of managed simulator processes

---

lib/run_loop/simctl.rb
spec/lib/simctl_spec.rb

`xcrun simctl help` was timing out when ensuring a valid CoreSimulator service after switching from Xcode 9 to Xcode 8.0.  This was causing unit and integration tests to fail.
Completes:
* run-loop: ensure valid CoreSim service can fail when switching from Xcode 8.0 to Xcode 9.0 [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/19609)

Simctl: can switch back to Xcode 8 after Xcode 9 is active

---

lib/run_loop/device.rb
lib/run_loop/plist_buddy.rb
lib/run_loop/simctl.rb
spec/lib/device_spec.rb
spec/lib/plist_buddy_spec.rb
spec/lib/simctl_spec.rb

In Xcode 9, many (more) plist are (more) lazily created after simulators are erased.  This can break some of the tooling which either assumes the plist exist or waits for the plist to exist.  Whenever run-loop needs to reference a plist, it now ensure that plist exists by creating it.
Progress on:
* run-loop: cannot set language if AppleLanguage key does not already exist [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/19809)

Device: ensure simulator plist paths exist

---

lib/run_loop/plist_buddy.rb
spec/lib/plist_buddy_spec.rb
spec/resources.rb

Consider this command:
```
-c "Add :MyKey:0 string en"
```
If `MyKey` does not exist, then a new `Dict` container is created with one entry:
```
"0" => "en" (type String)
```
If `MyKey` exists and is an `Array`, then "en" is pushed onto the front of the list.
Because Xcode 9 (very) lazily creates various Simulator plists, run-loop has started creating empty plists if the expected ones do not exist (yet).
This can cause run-loop to add a `Dict` instead of an `Array` type container when setting the simulator language.
This pull request adds 2 methods to `PlistBuddy` to help run-loop correctly set the simulator language.
```
run_command(cmd, path, options)
unshift_array(key, type, value, path, options)
```
Completes:
* run-loop: PlistBuddy needs a way to interact with Array containers …

PlistBuddy can run arbitrary commands and push new values onto arrays

---

lib/run_loop/device.rb
spec/integration/core_simulator_spec.rb
spec/lib/device_spec.rb

Completes:
* run-loop: cannot set language if AppleLanguage key does not already exist [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/19809)

Device: use PlistBuddy#unshift_array to set Simulator language

---

lib/run_loop/http/retriable_client.rb

iOS 11 devices are sometimes in this state.
Completes:
* run-loop: DeviceAgent HTTP clients needs to retry on Errno::EHOSTUNREACH [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/22073)

HTTP: client retries on unreachable host

---

lib/run_loop/device_agent/client.rb

As with the main `calabash-ios` repo:
The previous URL is 404ing now as the owner got a cease and desist from Apple. Apple now have official documentation on XCTest.

Updated XCUIElementType documentation

---

lib/run_loop/core.rb
lib/run_loop/xcode.rb
spec/lib/core_spec.rb
spec/lib/xcode_spec.rb

Completes:
* As a tester I want to use run-loop with Xcode 9.1 [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/24757)

Xcode: add support for 9.1

---

.travis.yml
lib/run_loop/dylib_injector.rb
spec/lib/dylib_injector_spec.rb

Starting in Xcode 9, some apps are slow to launch completely.
If lldb tries to dlopen before the app is ready, the app launch will never complete - even on a retry.
Completes:
* As a run-loop user, I want to delay dylib injection because my app is slow to start [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/24761)

DylibInjector: user can add delay before injecting

---

lib/run_loop/core_simulator.rb

Progress on:
* UITest, XCUITest, Appium, App Center, and Calabash support for Xcode 9.3 [VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/33617)
When testing run-loop or iOSDeviceManager, it is possible for your machine to run out of process identifiers because of orphaned CoreSimulator services.   This often happens during Xcode beta testing and it forces a machine reboot.
This is not a new problem.  In the past, we have maintained a list of CoreSimulator services that we manage.  Xcode 9.3 betas have forced us to be more aggressive about managing the processes.
```
RunLoop::CoreSimulator.terminate_core_simulator_processes
```
`RunLoop::CoreSimulator.terminate_core_simulator_processes` called automatically when launching a simulator and then launching an app on …

Improve CoreSimulator Services process management

---

lib/run_loop/device_agent/client.rb

Added new method for DeviceAgent client which will be used in Cucumber tests.
[VSTS](https://msmobilecenter.visualstudio.com/Mobile-Center/Krukow-M1-Team/_workitems/edit/34509)

Add element_types method to DeviceAgent client

---

lib/run_loop/ipa.rb
spec/lib/ipa_spec.rb

When we grab test run assets from App Center, the `.ipa` is usually named `app`.
The previous implementation of `RunLoop::Ipa` did not allow instances to be created from paths that did not end with a `.ipa` extension.
Allowing `Ipa` instances to be created from extension-less zip files will help automate the process of debugging App Center test runs.

Ipa: create instance from extension-less zip archives

---

lib/run_loop/shell.rb
spec/lib/shell_spec.rb

This is a very common pattern:
```
start = Time.now
hash = RunLoop::Shell.run_shell_command(...)
elapsed = Time.now - start
RunLoop.log_debug("... took #{elapsed} seconds")
```
`run_shell_command` already tracks the elapsed time so that it can timeout the shell command.
After this change, we can update the code above to:
```
hash = RunLoop::Shell.run_shell_command(...)
RunLoop.log_debug("... took #{hash[:seconds_elapsed]} seconds")
```

Shell: output of Shell#run_shell_command includes elapsed time

---

lib/run_loop/instruments.rb
spec/resources/instruments_output.rb

New instruments behavior!
```
null () [<udid>]
```

Instruments: ignore devices without name or version

---

lib/run_loop/directory.rb
spec/integration/directory_spec.rb
spec/lib/directory_spec.rb

While creating deploy/ios clear-app-data tests for Calabash, I noticed that my .app was being re-installed between test runs.  This should not happen because the local .app was the same as the .app that was (already) installed on the simulator.  This was causing the clear-app-data tests to fail because the re-install was wiping the app data.
This implementation returns the expected result:  the local .app and the installed .app have the same digest after `xcrun simctl install <app>`.

Dir#digest: change how cumulative digest is computed

---

lib/run_loop/core_simulator.rb
lib/run_loop/device.rb

We are migrating to Jenkins 2.0.  We have seen that jobs that use iOS Simulators are not stable.
In Jenkins 1.0, I ran a nightly job that "doctored" the iOS Simulators - erased all simulators and booted them so they would be ready for testing.  
I ran that job this morning and discovered a couple of interesting things:
1. Xcode 8.3.3 can launch iOS 11.0 and 11.1 simulators
2. Xcode 9.2 can launch iOS 8.2 simulators
In the case of Xcode 8.3.3, I discovered that the simulator-stable heuristic was not working for iOS > 10 - we were waiting for 240 seconds for the simulator to stabilize.
This pull request updates the heuristic for iOS > 10 on Xcode 8.3.3 so we will not wait for 240 seconds.
Since Xcode 9.2 appears to launch the same simulators as Xcode 8.3.3 + iOS 11.2 simulators, we can …

Improve simulator "wait for stable" heuristic

---

lib/run_loop/core.rb

[Azure DevOps](https://msmobilecenter.visualstudio.com/Mobile-Center/_workitems/edit/46616)
New device models no longer support convention being called `iPhone #{xcode.major_version - 1}`

Core: fix default simulator for Xcode 10

---

run_loop.gemspec

The version is quite outdated, in this way users are able to decide which version they want to use
Fixes #583

Do not bind run_loop to any versions of json

---

lib/run_loop/simctl.rb
spec/lib/simctl_spec.rb

**Problem:** In new Xcode `xcrun simctl list devices --json` returns different output. With new output old run-loop availability check does not work.
**Root-cause:**
New JSON output from Xcode 10.1 beta 2 contains different parameters, e.g.:
```
{
"state" : "Shutdown",
"isAvailable" : "YES",
"name" : "iPhone 8",
"udid" : "BF6DFF2F-BF46-4348-AEFF-F676EE61A43E",
"availabilityError" : ""
}
```
VS
Output from Xcode 10:
```
{
"state" : "Shutdown",
"availability" : "(available)",
"name" : "iPhone 8",
"udid" :  "BF6DFF2F-BF46-4348-AEFF-F676EE61A43E"
}
```
So we need to verify `isAvailable` and old `availability` parameters.
---
All tests passed locally with Xcode 10.1 beta 2.

Fixed simulators availability check.

---

lib/run_loop/regex.rb

- Changed regex to include new devices
This fix needed to enable iOSDeviceAgent tests locally.
```
Akvelon 8 (12.1) [c25eb5ffd7f1468b1adbafb684b34339ac67c950] - old device id format
Akvelon XS Max (12.0.1) [00008020-00196D9E3650003A] - new device id format
Apple TV (12.1) [DF19D6B2-C13A-4194-BF5E-0DBEA88A53DB] (Simulator) - simulator id format
```

Fixed regex for new device ids.

---

lib/run_loop/core_simulator.rb
spec/lib/core_simulator_spec.rb
spec/lib/shell_spec.rb
spec/lib/xcrun_spec.rb

**Issue:**
Test fails in `run_loop/spec/integration/core_simulator_spec.rb`
`RunLoop::CoreSimulator#launch_simulator does not relaunch if the simulator is already running`
Test fails with error message:
`DEBUG: Simulator relaunch required: simulator was not launched by run_loop`
**Root cause:**
`running_simulator_details` function searches the first process with substring `MacOS/#{sim_name}`.
On Mojave there are two processes that matches this substr:
```
6055 /Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/SimulatorTrampoline.xpc/Contents/MacOS/SimulatorTrampoline
6105 /Xcode/10.2/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator -CurrentDeviceUDID 6DE7902E-CAD6-4949-9037-C1A0319991FF -ConnectHardwareKeyboard 0 …
```

Simulator process is determined incorrectly during simulator relaunch

---

lib/run_loop/simctl.rb
spec/lib/simctl_spec.rb

The output format of `xcrun simctl list devices --json` seems to have changed the type of  `isAvailable`. It a boolean value now instead of "YES" or "NO".
```bash
09:56 $ xcrun simctl list devices --json
{
"devices" : {
"com.apple.CoreSimulator.SimRuntime.watchOS-5-1" : [
],
"com.apple.CoreSimulator.SimRuntime.tvOS-12-1" : [
],
"com.apple.CoreSimulator.SimRuntime.iOS-12-1" : [
{
"state" : "Shutdown",
"isAvailable" : true,
"name" : "iPhone 5s",
"udid" : "0C944D5C-DCF5-4FD5-9AD6-34091735FDF0"
},
{
"state" : "Booted",
"isAvailable" : true,
"name" : "iPhone 7",
"udid" : "6D73A12B-F34E-4132-BE05-97355B98506B"
},
{
"state" : "Shutdown",
"isAvailable" : true,
"name" : "iPhone X",
"udid" : "5E963272-CE3B-4161-A6EE-EC4F44AF53F5"
},
{
"state" : "Shutdown",
"isAvailable" : true,
"name" : "iPhone …
```

Fix check for available simulators

---

lib/run_loop/core_simulator.rb
lib/run_loop/sim_keyboard_settings.rb

When you open keyboard for the first time, it shows tutorial for Swipe keyboard using.
We should disable this tutorial to fix keyboard tests

Fix keyboard on iOS 13

---

azure-pipelines.yml
lib/run_loop/core.rb
lib/run_loop/device.rb
lib/run_loop/xcode.rb
spec/integration/simulator_compatibility_spec.rb
spec/lib/xcode_spec.rb

**Changes:**
1) Include configuration `Mojave + Xcode 10.3` to the yml file
2) Fix `ios_version` on Xcode 10.3
Previously we used mapping `ios_version.minor = xcode_minor` but `Xcode 10.3` contains simulators for `12.4`
3) Refactoring:
- Moved logic to get default simulator to the Xcode class
- Moved logic to get ios_version to the Xcode class
The main advantage of this refactoring is that we can reuse this logic in other services.
For example, the following logic exists in `calabash-ios-server` too
```
version = xcode.version
xcode_major = version.major
xcode_minor = version.minor
major = xcode_major + 2
minor = xcode_minor
```
4) Add tests to cover new logic

Add support for Xcode 10.3

---

spec/integration/detect_simulators_spec.rb

We have found problem with `Instruments and Simctl agree on the simulator count` test, this test randomly fails, but always pass when we run single test.
It fails because xcode `instruments` simulators count is cached and not equal xcode `simctl` simulators count.
As fix we have initialized new instances of classes `Instruments` and `Simctl` to avoid caching.
Note: this issue randomly reproduces on all xcode versions.

Fix unstable simulators count test

---

lib/run_loop/core_simulator.rb
lib/run_loop/device.rb
lib/run_loop/l10n.rb
lib/run_loop/xcode.rb
spec/lib/core_simulator_spec.rb
spec/lib/l10n_spec.rb
spec/lib/xcode_spec.rb

Small improvement for run-loop that will be very helpful for springboard-alert tool since it depends on CoreSimulator path.
1) Add method `core_simulator_dir` to Xcode class
2) Fix all places where the path is hardcoded
3) Fix existing tests
4) Add new tests

Add special method for CoreSimulator directory

---

lib/run_loop/xcode.rb
spec/lib/xcode_spec.rb

`iPhone Xs` simulator was removed from default simulator list in `Xcode 11 GM seed 1`. Replace it to `iPhone 11`

Change default device for Xcode 11.0

---

lib/run_loop/device_agent/client.rb

Problem: sometimes, while cucumber tests execute, we can face error "Could not connect to the DeviceAgent service" (health check is failed).
Solution: try to relaunch DeviceAgent and repeat health check.

Add relaunch DeviceAgent, when error "Could not connect to the DeviceAgent" is occured.

---

lib/run_loop/device_agent/ios_device_manager.rb
lib/run_loop/device_agent/runner.rb
lib/run_loop/environment.rb

This is to support the changes to the DeviceAgent repo for using a custom port for running the tests https://github.com/calabash/DeviceAgent.iOS/pull/373/commits/07c0142271c183e038fe7f277f826adc249a1af7

Add passing the port from the env variables

---

lib/run_loop/device_agent/ios_device_manager.rb

There were a little mistake in the `ios_device_manager.rb` file, which caused a test failure with `no implicit conversion of Integer into String` error.
This PR should fix this error.

Fix "conversion of Integer into String" error

---

lib/run_loop/directory.rb

Fixed this deprecation because it was throwing warnings on ruby 2.7.0 environment.

Fixed warning 'Using the last argument as keyword parameters is deprecated'

---

run_loop.gemspec

Hello,
I was trying to use on a local project the functionality of `i18n` gem:
`I18n.config.interpolation_patterns`
But it seemed to not exist :(
I tracked it down to the enforcing of the version `< 1.0` from the `run_loop` gem
I checked the usage of such dependency in this project and it seemed to me that the usage is very basic and a higher version of `i18n` could be used
Hence the PR :),
Maybe I am wrong and/or maybe it could be updated even further maybe `<2.0` ?

Update maximum version of 'i18n' dependecy

---

lib/run_loop/device_agent/client.rb

The http calls are called multiple time before each single calabash interaction. There is no need in that in case automatic dismissal was disabled beforehand.

Skip springboard alert check if automatic dismissal was disabled
